### ISSUE TITLE
ARM compatibility?

### ISSUE THREAD

**Issue by pdarcos** [chris-belcher/electrum-personal-server#1]
Hi Chris,

Thanks so much for your contribution! I was waiting for something like this to come around.

I already managed to get my old cubox (ARM) to run a full node (0.16) and that was quite an experiment.

How much overhead does EPS add to an already working full node like mine?

Once I find some spare time I plan on trying to get EPS running on my cubox https://www.solid-run.com/nxp-family/cubox-i/

Keep up the excellent work. This spirit is what first got me into bitcoin way back in the early days. Glad to see it is still alive.

Cheers

**Comment by chris-belcher** [comment]
> How much overhead does EPS add to an already working full node like mine?

I don't know, probably not very much at all. I'd suggest trying it to see, and report back how much it is.

**Comment by 0xbytes** [comment]
I run a bitcoin node 0.16 + personal electrum server (PES) on raspberry pi 3 with latest raspbian OS. 
Starting the PES takes 100% CPU for 65 seconds. Once it is up and running, PES shows 7% or less CPU when I connect with my electrum wallet from PC or my android phone.   

PES is a lot slower on a raspberry pi during the initialization stage as compared to my 8 core Intel PC, but once PES is initialized, not much of a performance difference is noticed during bitcoin transactions.

tx.

**Comment by chris-belcher** [comment]
Great report, thanks!

**Comment by 0xbytes** [comment]
Update: I also run bitcoin node 0.16 + personal electrum server (PES) on odroid c2 running dietpi OS. Odroid is the same size as raspberry pi but more powerful for few $ more. 
Starting the PES takes 100% CPU for 20 seconds (much faster than raspbian OS).
