### ISSUE TITLE
Move command line options to the config file

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/electrum-personal-server#100]
Some options like the location of the log file, whether text is appended, what debug level, etc are configured on the command line. This is slightly confusing given all other options are in the `config.cfg` file. It would be nice to move those options to that file instead.

**Comment by BobleChinois** [comment]
Hi, I've started working on it, I'm very unexperienced so not sure how to handle it. I'll make a pull request soon so that we can see how to tackle that.

**Comment by suvayu** [comment]
@BobleChinois feel free to tag me on the PRs, since I added those command line flags, and should be able to provide feedback.

**Comment by chris-belcher** [comment]
I'm working on this now too, because its a nice-to-have prerequisite for packaging up the project in a binary created by pyinstaller on Windows.
