### ISSUE TITLE
electrum wallet in other pc

### ISSUE THREAD

**Issue by Pindol83** [chris-belcher/electrum-personal-server#101]
Good morning,

i'm italian sorry for my bad english, i set up the electrum server in a pc with a full node, but the electrum wallet is in to another pc, so in the config file i put the ip address of the pc with electrum wallet under host = 192.168.xx.xx but it doesn't won't to start the electrum server (OSError: [Errno 49] Can't assign requested address)

if i put 0.0.0.0 there are no problems and it connects normally,  (INFO:2019-04-10 11:35: Electrum connected from ('192.168.xx.xx', 50570) but with this settings i think that my electrum server is open to anyone it's correct?

how can i set the config to accept the connection only from the ip of my pc with electrum wallet?

thanks

**Comment by ejose19** [comment]
If you're following this guide:

https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_64_electrum.md

Then you can use 0.0.0.0 and limit access using the firewall:

> sudo ufw allow from 192.168.0.0/24 to any port 50002 comment 'allow EPS from local network'

That way computers outside your network won't reach the eps server

The other option without the firewall is to leave 0.0.0.0 and use the ip_whitelist = 192.168.0.0/24 so the limit is placed on the eps server (although the firewall option is preferred)
