### ISSUE TITLE
Please help test the windows packaged executable

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/electrum-personal-server#106]
I've created a windows packaged executable version of Electrum Personal Server which windows users could run without needing to install python or anything else.

If you run Windows OS, please download (and check the signature) and run the file. On the command line run `electrum-personal-server config.ini` or drag the config file onto the .exe file. It should work the same as the regular EPS, obviously you need to configure the `config.ini` file.

The executable works on my virtual machine Windows 7, but I've read that sometimes pyinstaller executables have DLL issues.

[electrumpersonalserver-windows-exe.zip](https://github.com/chris-belcher/electrum-personal-server/files/3099491/electrumpersonalserver-windows-exe.zip)

signature:
```
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAABCgAGBQJcukjQAAoJEO9zTqZ38xEpP/wP/0syG3kxtgS5A4qmswtFc0Mz
mirBjM6hThsjswsXEW8nKPg2lCWW+AfjVAl3stXhKKfi7fLZK4HMmdXdn6gD5Di1
P+sFQ6JlE3XB95IbzSUYx0aCK7EIJ4ildmhaIQU+IkrXdPjTHl05AgFid+VLrmmu
xkdBFLSOLOtcc0K8bw9bI6mtuCT8SLuIwKuTmuRE8zCtAjhbi9bLRdTLYFfFFOvu
c8zBxp6ZujgMS4EE3wQccUdodncOVpJtvi3k9iibrOYASDQVnZ0GiQUttk2FDO+b
8k78kvwFHFopZMIFTPjq4xRM92JJqW8EPbR6xXeuh8MFwY3+EK4ukBPSYUSfOcXt
WMT/jpmQGQ2228hzEIYEBl3pXSfs5FGD8jOMpvfjH0afAKEzrTRNNJS5u0RAaaEm
7lWLl0KM9bmTGmtkPZrSBlTt4FQZqd/s/EEm1au4/3ZsyBhM30Ijn/Bgfy/+LyUa
BDGAck7fPRXbfMGAVM2+uT+osXaD0iWb0A4PTZotB9HWRP51b9ewiPBoj7cTCJqH
lzfWTxorBCAs+XrWSWf3MMvbw+2w+9Tmm00xs+hfEi+tzbgHXz8LzUUOnbEoL7hl
xu1M1XTQB0UExKQBPnFB66WQUxWHnIwnVsgFyIMqkeQkLmkgD8+VuzE1b5rZIGmB
KGFIH7+DNWYkPMmardEB
=29G7
-----END PGP SIGNATURE-----
```

**Comment by DriftwoodPalace** [comment]
This is awesome! 

Works for me on Windows 10.

**Comment by DriftwoodPalace** [comment]
I had one person reach out to me asking for help. We got it to work without any bigger issues, so at least one more data point that it works.

I think the biggest hurdle for a normal user now is the config-file. I don't think "non advanced" users are used to modifying the settings before starting a program. He who reached out to me had made a small error (not removing `#` before his MPK) and I think errors like that would be more common with more "normal" users.

**Comment by chris-belcher** [comment]
I think we were talking to the same person. That was the inspiration for these two commits https://github.com/chris-belcher/electrum-personal-server/commit/f506a9ebd4a0e9dbfafd72d81228ae149fb51be8 https://github.com/chris-belcher/electrum-personal-server/commit/6a7c621aa1d31df3716a10865125a28ed79c976e

**Comment by chris-belcher** [comment]
Release 0.1.7 is now out https://github.com/chris-belcher/electrum-personal-server/releases/tag/electrum-personal-server-v0.1.7 which includes a windows packaged binary.

**Comment by BobleChinois** [comment]
I just made a test with Windows 10 that was lying around, no problem, it's way easier like that

**Comment by yunier2002** [comment]
Working with no issues for me too on Windows 10. Great work guys!!

**Comment by chris-belcher** [comment]
This clearly works so I'm closing the issue, thanks everyone!
