### ISSUE TITLE
Pending transactions not showing up in electrum.

### ISSUE THREAD

**Issue by Nurdur** [chris-belcher/electrum-personal-server#107]
Should transactions that are waiting in the mempool be showing up in Electrum when connecting solely to electrum personal server? Mine aren't. Debating whether I should just wait for confirmation (going to be a while, I lowballed the fees since I'm just testing...), but this brought up two questions:

1) How do I know that the intended watch-only addresses were actually added to my core node? (I'm pretty new to the debug console and most of the commands I've tried to use so far have been deprecated.) I do see "iswatchonly": true when I use gettaddressinfo [address] in the debug console, so it seems to be loaded/registered with my core node..
2) Is there a way to re-trigger this: "The first time the server is run it will import all configured addresses as watch-only into the Bitcoin node, and then exit."? I made a few mistakes and so re-ran both /py scripts a bunch of times before getting everything (mostly) working.

Maybe my lowball fee (1.2 sat/b) doesn't make the cut for my own mempool (though I can see the tx as pending on oxt.me)?

Windows 10. Installed through python/powershell.

**Comment by chris-belcher** [comment]
1. One command useful for that is `getaddressesbylabel "electrum-watchonly-addresses"`. And yes, getaddressinfo can also be used for individual addresses.

2. The only way to do this is to delete or rename the wallet file (found in the bitcoin data directory and by default called `wallet.dat`) and then run electrum personal server again to import and rescan.

The lowball fee is a possibility, try the command `getmempoolinfo` which has a field `"mempoolminfee": 0.00001000` that tells you your minimum fee rate (which is 1 sat/b in my case)

You could also try `gettransaction <txid>` to check whether your node wallet knows about your transaction. Also try `getmempoolentry <txid>` and `getrawtransaction <txid>` which check whether the transaction is known to your node.

**Comment by Nurdur** [comment]
Thanks so much. Was taking me a long time (not that it wasn't fun!) digging through the core docs looking into this.

I think it's this: "mempoolminfee": 0.00001000 

As my fee was 1.2 sat/b, for a 1-input 1-output tx, the total tx fee was probably < 1000 sat, and more like 300 sat. I'll try messing with my node settings and see if I can get a big enough mempool. (I assume I can shut everything down, reconfigure my bitcoin.conf, and relaunch...)

Or maybe just wait a day or two and see what happens. Seems like I'd learn more this way, and I can always adjust mempool settings for future attempts.

I'll update with whatever I learn. Thanks again!

**Comment by Nurdur** [comment]
Just noticed that the 0.00001000 above was sat/kB... So maybe something else is going on. None of the specific transaction queries (getmempoolentry etc.) could find the transaction. So oxt.me sees it, but my node doesn't. I'll look further into my local mempool configuration.

getaddressesbylabel "electrum-watchonly-addresses" was very helpful. Lots of addresses listed, so they did get into my core's watch list successfully. Just not into my mempool.

**Comment by Nurdur** [comment]
This may not be helpful, but here's how it fixed itself...

I shut down bitcoin core and edited bitcoin.conf to increase my max mempool to 800 MB (was 300). Not that the mempool was anywhere near the 300 limit, but I thought I'd see what happened. Closing down my node caused eps to quit, but my two electrum wallets were left open, so I tried to quit them, getting "electrum has encountered a problem" or something close.

Started my bitcoin node. Ran the eps .py script, and it did the first time scan again. I ran the rescan script just in case, then (as instructed in the logfile) ran the eps script again to launch eps for real. I'm not sure why, but the bitcoin node now noticed 1 of my 2 so-far invisible transactions. The other was listed as "pending". Not sure how that happened on a Wasabit to Electrum send, but when I clicked "broadcast", my node could now see both transactions. I opened both wallet .json files in electrum and now I see both transactions pending in the mempool, listed in electrum as unconfirmed.

Now when I try gettransaction, my node can see both transactions.

Sorry, I'm not sure what caused the initial script behavior to re-trigger, and wonder whether it was that or two crashed/confused electrum instances, but everything's working now. I'll close the issue. Still glad for the help I got from posting, I was quite confused at first. (Still am, I guess, but less so!)

Thanks Chris.

**Comment by s7n4qg3** [comment]
> You could also try `gettransaction <txid>` to check whether your node wallet knows about your transaction. Also try `getmempoolentry <txid>` and `getrawtransaction <txid>` which check whether the transaction is known to your node.

My node hasn't detected an unconfirmed tx (i.e. the tx appears on a block explorer, but when I try the above commands, I get 'Transaction not in mempool' or 'No such mempool transaction').

According to jochen-hoenicke.de, there are currently ~18k transactions in the mempool, and the mempool size is ~8MB, but when I try 'bitcoin-cli getmempoolinfo', I get the following readout:

{
  "size": 7045,
  "bytes": 2983678,
  "usage": 12172352,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000
}

I assume this means that my node isn't detecting all mempool transactions, but I don't understand why...Can someone help?

By the way, I'm running the most recent version of bitcoin core, and here's my bitcoin.conf:

daemon=1
server=1
prune=75000
rpcpassword=REDACTED
rpcport=8332
rpcuser=REDACTED
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
proxy=127.0.0.1:9050
bind=127.0.0.1
onlynet=onion
dnsseed=0
dns=0

**Comment by chris-belcher** [comment]
@s7n4qg3 Your getmempoolinfo result shows that your nodes own mempool has only 2.9 MB worth of transactions. Looking at the records from my own node, it also had around 8MB around the time you posted.
So it seems your node doesn't get some unconfirmed transactions for some reason. It probably means your node isn't very well connected to the rest of the p2p network.

If your transaction gets mined into a block then it should definitely appear to your node then. One thing you could try is obtaining the transaction hex string of your transaction (perhaps from a blockchain explorer API) and giving it to your node with the RPC command `sendrawtransaction <txhex>`. I've found [this explorer API](https://blockchain.info/rawtx/a324ddc001fee0b9d97201f24cad578831ee475f3b1841666c01529d59bdd909?format=hex) which works (using a random txid I got from my node's mempool)

**Comment by s7n4qg3** [comment]
Thanks Chris. I agree, it seems to be an issue with my node.

Right now, there are ~33k tx in the mempool (~16 MB) according to jochen-hoenicke.de, but my node gives the following when I try bitcoin-cli getmempoolinfo:

{
  "size": 19685,
  "bytes": 9579243,
  "usage": 36254432,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000
}

So I'm still not getting the full mempool for some reason.

I've been running my node for several hours (and had been running it for a while when I made my earlier comment). I'm currently connected to 8 other nodes according to bitcoin-cli getnetworkinfo, so I'd be surprised if the issue is caused by a poor connection to the P2P network.

Your sendrawtransaction <txhex> idea worked like a charm btw! The tx appeared in electrum a few seconds later.
