### ISSUE TITLE
Large number of addresses in initial import

### ISSUE THREAD

**Issue by kk2iuy** [chris-belcher/electrum-personal-server#108]
I have a multisig wallet with a large number of addresses (50,000). I have added the list of master pub keys and have set the initial_import_count = 50000

It takes about an hour to obtain the addresses to import, but when it is done on Bitcoin Core only 6,000 addresses have been imported. After I rescan and open the electrum client the balance of all the combined wallets is wrong (lower than it should be), I'm assuming because it didn't do a full import of the addresses.

Is there a limit in the number of addresses being imported?

I'm using this to get the list of addresses imported:

`bitcoin-cli listreceivedbyaddress 0 true true`

When I start electrum-personal-server again in the logs it shows already-imported addresses as a list of 2,000 addresses.

**Comment by chris-belcher** [comment]
Thanks for the issue.

I'm not aware of any limitation but I'll ask some other Core developers who might know.

**Comment by kk2iuy** [comment]
Thanks for the quick reply. I got round it by putting all the 50,000 address in one line in the [watch-only-addresses] section and that seemed to work. Importing them into Core only took a few mins. 

I will try again with the new version using the master pub keys.

I have another issue related to this import though - not sure if I should create another issue for it, but on Bitcoin Core when I call listtransactions I can see all the transactions there with the correct number of confirmations. When I call the history function in electrum all the incoming transactions have the correct number of confirmations, but all the outgoing transactions show 0 confirmations for all of them.

I will try this first with the new version before investigating further.

Thanks

**Comment by chris-belcher** [comment]
I'll try to replicate this soon by creating a multisig wallet on regtest and creating 50000 transactions on it.

**Comment by kk2iuy** [comment]
Just to confirm it's 50,000 addresses with about 1,000 transactions. These 50,000 addresses were given out to customers to deposit Bitcoin, not all have been used yet, but may be used in the future so the transactions are spread out. 

e.g. 
wallet 1 has an incoming transaction
wallet 2 to 1,300 have no transactions
wallet 1,301 has a transaction
wallet 1,302 has no transactions
wallet 1,303 has a transaction
etc

**Comment by chris-belcher** [comment]
Just to check, do you need to raise the gap limit too? 50000 addresses with 1000 transactions implies an average of 50 empty addresses between every used one.

**Comment by kk2iuy** [comment]
No I have kept the gap limit at 25. From my understanding,  if I know the addresses that need to be monitored and generate them myself and import them (using the initial_import_count) then I believe all of them will be checked. The gap limit will apply if I allow it to automatically generate (to "discover") derived addresses that could potentially have a UTXO. Please let me know if I haven't understood this correctly.

I've added the master pub keys to the new config and ran it with version 0.1.7 and everything seems to be working correctly. The balances and transactions are up to date so I'm going to close this issue. Thanks for your help and the great work you're doing here.
