### ISSUE TITLE
Electrum can't find EPS

### ISSUE THREAD

**Issue by iY3is** [chris-belcher/electrum-personal-server#11]
When I run ./server.py, EPS builds my address history and starts listening for Electrum wallet on 127.0.0.1, 50002. However, when I start Electrum, I can't find 'localhost' in the Tools > Network > Server menu, so I can't connect to EPS.

I'm running up to date versions of Linux Mint, Bitcoin Core, lnd, Electrum, and a hardware wallet, with everything saved in default locations.

Here's my bitcoin.conf:

txindex=1
rpcuser=OMITTED
rpcpassword=OMITTED
server=1
rpcport=8332
daemon=1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332
maxconnections=10

When I run netstat -l, I get this:

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:28332         *:*                     LISTEN     
tcp        0      0 localhost:8332          *:*                     LISTEN     
tcp        0      0 *:8333                  *:*                     LISTEN     
tcp        0      0 localhost:50002         *:*                     LISTEN     
tcp        0      0 localhost:46453         *:*                     LISTEN     
tcp        0      0 legendarybirds:domain   *:*                     LISTEN     
tcp        0      0 localhost:ipp           *:*                     LISTEN     
tcp6       0      0 ip6-localhost:8332      [::]:*                  LISTEN     
tcp6       0      0 [::]:8333               [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:ipp       [::]:*                  LISTEN     

Here's an excerpt from my debug.log (the bottom rows repeat every 30 seconds):

00:26:18,906891 [  LOG] Found 79 txes. History built in 0.5241124629974365sec
00:26:18,907108 [  LOG] Starting electrum server
00:26:18,907187 [  LOG] Listening for Electrum Wallet on ('127.0.0.1', 50002)
00:26:48,920511 [DEBUG] on heartbeat listening
00:26:48,920890 [DEBUG] listtransactions tx_request_count=2
00:26:48,924491 [DEBUG] recent tx index = 0 ret = [('OMITTED', 'OMITTED'), ('OMITTED', 'OMITTED')]
00:26:48,924718 [DEBUG] last_known_wallet_txid = ('OMITTED', 'OMITTED')
00:26:48,924901 [DEBUG] check4con unconfirmed_txes = {}

Does anyone know what I'm doing wrong? Thanks in advance.

**Comment by fivepiece** [comment]
Hi, you can set the server manually by unchecking the `Select server automatically` checkbox.

![image](https://user-images.githubusercontent.com/5624963/38287861-c72910a8-37d5-11e8-81c8-d351a2c1cec6.png)

**Comment by iY3is** [comment]
Thanks @fivepiece - it's working now :-)
