### ISSUE TITLE
Wallet related RPC call failed

### ISSUE THREAD

**Issue by Synaptyk** [chris-belcher/electrum-personal-server#111]
Hello, I am needing some help. When I try to start EPS I get the following errors:

> INFO:2019-05-01 01:59:08,969: Starting Electrum Personal Server
> INFO:2019-05-01 01:59:08,970: Logging to C:\Users\Synaptic\AppData\Local\Temp/electrumpersonalserver.log
> DEBUG:2019-05-01 01:59:08,971: obtaining auth from .cookie
> ERROR:2019-05-01 01:59:08,985: JsonRpcError({'code': -18, 'message': 'Requested wallet does not exist or is not loaded'})
> ERROR:2019-05-01 01:59:08,987: Wallet related RPC call failed, possibly the bitcoin node was compiled with the disable wallet flag
> 

I have already added disablewallet=0 to my bitcoin.conf but the issue persists. I can't get past this point.

This is what my bitcoin.conf looks like:

> datadir=X:\Bitcoin\Bitcoin-mainnet
> server=1
> disablewallet=0

This is running off an external harddrive. any suggestions?

**Comment by chris-belcher** [comment]
That error is related to Core's multiwallet feature.

Multiwallet mode is activated if bitcoin.conf has multiple wallet lines, eg:

> wallet=wallet-file1.dat
> wallet=wallet-file2.dat

To make EPS use one of those files, set in config.ini this:

> wallet_filename = wallet-file1.dat

`wallet_filename` is blank by default, that is used when Core is not in multiwallet mode. So maybe your error is because you accidently set `wallet_filename` to something ?

**Comment by Synaptyk** [comment]
Thanks, I will try that. I had Pierre Rochard's node launcher also previously installed on this computer, which I believe might had something to do with my error.  So I decided to uninstall and delete everything, so now the blockchain is re-downloading. I'll also try your solution and report back if the problem persists.

**Comment by Synaptyk** [comment]
I have it working now after deleting node launcher, the blockchain, and re downloading everything. I also launched bitcoind instead of the gui. I was using the gui before. I don't know if that causes a difference in being able to connect the EPS.
