### ISSUE TITLE
Speeding up address generation

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/electrum-personal-server#112]
Electrum Personal Server uses pure python ECC code. This makes it easier to install because there's no dependencies, but also can make the startup very slow because the application has to do many EC calculations to convert the master public key(s) into addresses.

There's two possible ways to speed this up:

1. Improve the ECC code. Right now its copypasted from crappy experimental code from 2014 written by an unqualified idiot.

2. Implementing caching of addresses.

**Comment by cold-reaver** [comment]
I did a bit of a rewrite for an internal project, it speeds it up greatly by using multiprocessing. I also added multiple connection support but it needs some debugging. Ill put it up end of next week but it might have some edits/changes you personally wouldn't want.

I did some tests with an external lib in c and cython, but u'll get a dependency hell.

**Comment by chris-belcher** [comment]
Thanks for the effort. It will be interesting to see.

**Comment by MaDeRkAn** [comment]
@cold-reaver any progress ? We (I :P) need this very much.

**Comment by chris-belcher** [comment]
This can be solved with Bitcoin Core's descriptors and the RPC calls `deriveaddresses` and `importmulti`

**Comment by chris-belcher** [comment]
This recent commit https://github.com/chris-belcher/electrum-personal-server/commit/3e52ed9e11aab176fa2d8e8c619a9cae568424d4 uses the RPC call `deriveaddresses` to generate addresses. It results in a huge massive speedup in address generation. And no new dependencies are needed.

However it does require Bitcoin Core 0.20.0 or higher, which is scheduled to be released in a few weeks. For now I've been running this on the release candidate.

Also, as of this particular commit importing addresses for the first time is still quite slow. But that can be fixed by writing code making use of the `importmulti` RPC call.

**Comment by chris-belcher** [comment]
This commit https://github.com/chris-belcher/electrum-personal-server/commit/c6b4b370e7ea0bb3643bc679dd1a6dc4625da48e uses the RPC call `importmulti` to import addresses much faster.

Some of you who have low powered devices like Raspberry PIs should try running the master branch of EPS, you'll also need the Bitcoin Core 0.20 release candidate. The speedup should be huge.
