### ISSUE TITLE
0.1.7 pip install created deprecated electrum-personal-server-rescan

### ISSUE THREAD

**Issue by seth586** [chris-belcher/electrum-personal-server#113]
I installed eps 0.1.7 in a fresh jail, and noticed that it installed two scripts in `/usr/local/bin`: 
```
electrum-personal-server
electrum-personal-server-rescan
```

Perhaps this is intentional to maintain backwards compatibility?

**Comment by chris-belcher** [comment]
Yes it's for backward compatability.

If you run that script then it will output a warning: https://github.com/chris-belcher/electrum-personal-server/blob/master/electrumpersonalserver/server/common.py#L824-L825
