### ISSUE TITLE
iOS wallet compatibility with eps

### ISSUE THREAD

**Issue by walletofsatoshi** [chris-belcher/electrum-personal-server#116]
Is there any iOS compatible wallet that can connect to eps ? If not is there any progress on electrum iOS?

**Comment by chris-belcher** [comment]
Try reading issue #33 it might be helpful.

**Comment by walletofsatoshi** [comment]
Sorry I was not clear earlier. I meant is there a wallet that I can run on iPhone and connect to eps since we don’t have electrum wallet for iPhone yet?

**Comment by chris-belcher** [comment]
Oh I see. I don't know sorry.

**Comment by BobleChinois** [comment]
iOS sucks for Bitcoin wallets. I never heard of a wallet that would allow you to connect to EPS. It seems that hodlwallet allows you to point to a node, Green should have some interesting features too, but I don't use neither of them myself.

**Comment by walletofsatoshi** [comment]
Zap wallet is an excellent wallet I can recommend for IOS . You can connect to your own node and have lightning and mainnet both wallets. Still in beta but the way they are developing I am so impressed. Been trying it out since it’s inception. Looking forward to it’s full release.
