### ISSUE TITLE
WARNING:: Address not known to Electrum Personal server, hash(address) =

### ISSUE THREAD

**Issue by jc-jnet** [chris-belcher/electrum-personal-server#117]
I had a similar issue to another reported issue related to fee bumping, although in this case I did not change the transaction fee myself.

(After a double spend, Electrum can't connect to EPS any more #89, https://github.com/chris-belcher/electrum-personal-server/issues/89).

I created a Trezor hardware wallet (with a passphrase). Sent BTC to it from another electrum trezor wallet using same EPS. Nothing appeared, although I can see it in the corresponding trezor.io/wallet. Thought it might be related to the 'unknown blocks' warning on my bitcoin core full node, so I upgraded from bitcoin core 17.0 to 18.0. The 'unknown blocks' warning has gone away, but I still can't see the transaction in the electrum wallet.

I have imported the transaction into this electrum wallet, but I am unable to broadcast it. Get the follwing error from electrum:

"The server returned an unexpected transaction ID when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Server returned unexpected transaction ID."

This is presumably related to the EPS warning:

"WARNING:2019-05-14 09:51:47,511: Address not known to server, hash(address) = .
This means Electrum is requesting information about addresses that are missing from Electrum Personal Server's configuration file."

**Comment by jc-jnet** [comment]
Could be due to new addresses being created by the passphrase of the trezor wallet? These are possibly unknown to EPS?

**Comment by chris-belcher** [comment]
Check whether you've imported the master public key(s) correctly. EPS prints out the first three addresses of each key, so check that they really are addresses you expect. Go to Electrum Wallet -> Information to get the right master public key.

If by passphrase you mean [this thing](https://en.bitcoin.it/wiki/Seed_phrase#Two-Factor_Seed_Phrases) then yes that creates a whole new wallet.

**Comment by jc-jnet** [comment]
That was it. I forgot to rescan and import the new wallet addresses.

**Comment by sunknudsen** [comment]
Having a similar issue playing around with testnet.

Configured a 2 of 3 multisig using two Electrum Wallets and a Trezor.

In `Information`, I see the three cosigners.

```
cosigner 1 ( keystore: bip32 )
cosigner 2 ( keystore: hw[trezor] )
cosigner 3 ( keystore: bip32 )
```

Not sure what the radio buttons are for as they all have the same `Vpub` master public key.

In `config.ini`, I configured `testnet_multisig_wallet = 2 Vpub...` but the first 3 addresses shown by `electrum-personal-server ~/path/to/config.ini` don’t match the ones found in `Addresses`.

According to the docs, I should append three master public keys after the 2 but I only have one in Electrum. Am I doing something wrong?

Example from the docs:

```
multisig_wallet = 2 xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF
```

**Comment by chris-belcher** [comment]
@sunknudsen There's definitely something wrong if all three cosigners have the same master public key. That's the first thing you should try to fix.

For a 2-of-3 multisig there should be the number 2 and then 3 master public keys, the master public keys could be repeated (although as above, if all the privkeys are the same then that doesn't create a real multisig wallet)

**Comment by sunknudsen** [comment]
Thanks for the follow up @chris-belcher. I’m new to Bitcoin but have some cryptography experience. Isn’t it normal for all cosigners to have the same master pub key from which receiving addresses are derived? I’m guessing if they are all on the same "wallet", they should have the same receiving addresses. Perhaps I have this all wrong.

**Comment by sunknudsen** [comment]
Think my issue might be related to https://github.com/spesmilo/electrum/issues/4777. Investigating.

**Comment by sunknudsen** [comment]
Electrum [bug](https://github.com/spesmilo/electrum/issues/4777) confirmed.

Until a fix is pushed to production, it’s possible to get master public keys using the Electrum console (View/Show Console).

```
[k.xpub for k in wallet.get_keystores()]
```

**Comment by chris-belcher** [comment]
Interesting, so it was an Electrum bug.

> Isn’t it normal for all cosigners to have the same master pub key from which receiving addresses are derived

Definitely not, because that means all the cosigners have the same private keys too. So its enough to compromise just one of them in order to steal the money, making the multisig wallet have the same security as a single sig wallet and therefore the multisig part would be pointless.

**Comment by sunknudsen** [comment]
> Definitely not, because that means all the cosigners have the same private keys too. So its enough to compromise just one of them in order to steal the money, making the multisig wallet have the same security as a single sig wallet and therefore the multisig part would be pointless.

Now that I think about it, that makes way more sense. Thanks @chris-belcher!

**Comment by dsche-cyber** [comment]
> Example from the docs:
> 
> ```
> multisig_wallet = 2 xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF
> ```

It seems like this example vanishes from the docs. Please get it into the HOW TO, I was facing the problem for a long time.

**Comment by chris-belcher** [comment]
What exactly happened @dsche-cyber?

**Comment by dsche-cyber** [comment]
> What exactly happened @dsche-cyber?
> 
> That example is still in the config file sample: https://github.com/chris-belcher/electrum-personal-server/blob/master/config.ini_sample#L19

Yeah, you are right. Didn't saw that. Was fully in reading the README.md. Probably you place it there too?
