### ISSUE TITLE
Using Kleopatra to verify issue

### ISSUE THREAD

**Issue by runjam1** [chris-belcher/electrum-personal-server#119]
I am getting this error message.
![Screenshot (59)_LI](https://user-images.githubusercontent.com/42794700/57722033-7d11a580-763a-11e9-8e72-92979e366037.jpg)

**Comment by chris-belcher** [comment]
I will try reproducing this when I need boot to windows.

**Comment by runjam1** [comment]
OK so two different developers?

**Comment by chris-belcher** [comment]
Yes
