### ISSUE TITLE
"authentication for JSON-RPC failed."

### ISSUE THREAD

**Issue by john-light** [chris-belcher/electrum-personal-server#122]
When I run the electrum-personal-server script, I get an authentication error:

```
electrum-personal-server /home/server/eps-v0.1.7/config.ini
INFO:2019-05-19 06:19:19,464: Starting Electrum Personal Server
INFO:2019-05-19 06:19:19,464: Logging to /tmp/electrumpersonalserver.log
ERROR:2019-05-19 06:19:19,722: Error with bitcoin json-rpc: JsonRpcConnectionError('authentication for JSON-RPC failed',)
^CTraceback (most recent call last):
  File "/home/server/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 726, in main
    bestblockhash[0] = rpc.call("getbestblockhash", [])
  File "/home/server/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line 84, in call
    response = self.queryHTTP(request)
  File "/home/server/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line 59, in queryHTTP
    raise exc
  File "/home/server/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line 51, in queryHTTP
    "authentication for JSON-RPC failed")
electrumpersonalserver.server.jsonrpc.JsonRpcConnectionError: authentication for JSON-RPC failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/server/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 731, in main
    time.sleep(5)
```

I found a similar issue here: https://github.com/chris-belcher/electrum-personal-server/issues/94

After commenting out the rpcusername and rpcpassword in both eps and bitcoind config files, as suggested in that thread, eps is starting successfully. However this seems like a hack. I was able to use 0.1.6 with an rpc username and password, I should also be able to use 0.1.7 the same way.

I tried some of the other debug methods mentioned in the #94 thread, such as commenting them out and then changing it back, and that doesn't seem to have an effect.

Any idea why the authentication might be failing and how I can fix it so I can use an rpc u+pw again?

**Comment by chris-belcher** [comment]
The issue must be somehow related to Bitcoin Core and EPS not being configured to use the same rpc user/pass.

Maybe your chosen rpc user/pass values has some special characters that stopped them from being properly read?

**Comment by john-light** [comment]
Hi @chris-belcher  thanks a lot for taking a look. After triple checking the values, I realized that I was using `rpcusername=` instead of `rpcuser=` in the `bitcoin.conf` file. After fixing this, EPS is now talking to bitcoind correctly. Closing this issue now - cause noted as user error :p
