### ISSUE TITLE
Recurring "Reconnecting RPC after error: BrokenPipeError"

### ISSUE THREAD

**Issue by hui-shen** [chris-belcher/electrum-personal-server#123]
Hi Chris,

I'm new to open source and EPS so apologies if this is a known issue.
I didn't find anything in the docs and issues of the project.

Running EPS 0.17 on Ubuntu 18.04.2.

Everything works as expected.
EPS is connecting to bitcoind 0.18 and Electrum wallet can connect to EPS.

However I notice in EPS logs I get **Reconnecting RPC after error: BrokenPipeError** every 30 seconds. Is this expected? Anything I should be worried about?

Thanks.

```
DEBUG:2019-05-26 10:04:00,023: unconfirmed_txes = defaultdict(<class 'list'>, {})
DEBUG:2019-05-26 10:04:00,023: reorganizable_txes = []
DEBUG:2019-05-26 10:04:30,052: on heartbeat listening
DEBUG:2019-05-26 10:04:30,053: listtransactions tx_request_count=2
DEBUG:2019-05-26 10:04:30,054: Reconnecting RPC after error: BrokenPipeError(32, 'Broken pipe')
... ommitted log lines
DEBUG:2019-05-26 10:04:30,060: unconfirmed_txes = defaultdict(<class 'list'>, {})
DEBUG:2019-05-26 10:04:30,060: reorganizable_txes = []
DEBUG:2019-05-26 10:05:00,088: on heartbeat listening
DEBUG:2019-05-26 10:05:00,088: listtransactions tx_request_count=2
DEBUG:2019-05-26 10:05:00,090: Reconnecting RPC after error: BrokenPipeError(32, 'Broken pipe')
```

**Comment by BobleChinois** [comment]
Hi, in my experience this isn't normal, does the wallet in Electrum sync (look at the dot in the right hand lower corner, is it green? Does the transaction show up correctly?)? It might be related to #102

**Comment by chris-belcher** [comment]
Thanks for the issue.

That line is this: https://github.com/chris-belcher/electrum-personal-server/blob/6de954ab7282817ee01ea447c84029421cef9c9b/electrumpersonalserver/server/jsonrpc.py#L63

So I think it's nothing to worry about. It's just telling you that the earlier RPC connection has ended and that it's creating a new connection. If your wallet shows your transactions correctly then there's nothing to worry about.

Maybe I'll edit those error messages to sound less scary.

**Comment by hui-shen** [comment]
@BobleChinois Yes Electrum is working fine (green)
@chris-belcher Thanks for confirming, I'll ignore these 'error'.
