### ISSUE TITLE
Dependence on wallet methods

### ISSUE THREAD

**Issue by maxsandova** [chris-belcher/electrum-personal-server#13]
I have a full node with the option `disablewallet=1`. I get the following error when running `setup.py`
```
Traceback (most recent call last):
  File "./server.py", line 473, in <module>
    main()
  File "./server.py", line 448, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 308, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/-----/.opt/electrum-personal-server-0.1.1/electrumpersonalserver/jsonrpc.py", line 58, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -32601, 'message': 'Method not found'}
```
It works fine if I enable a wallet, but this is not optimal, since I do not want to use an empty wallet and this could potentially attract spammers.

**Comment by chris-belcher** [comment]
Electrum Personal Server requires the bitcoin node wallet to be enabled. I don't see how enabling the wallet will be vulnerable to spammers.

**Comment by maxsandova** [comment]
* I think that the wallet requirement should be in the description of the program.
* More than a vulnerability, think of it as having a wallet  running which is not doing anything, better to not have one in that case. But if the wallet methods are required for most of eps functionallity, then feel free to close this issue.

**Comment by chris-belcher** [comment]
* It says so in the readme. https://github.com/chris-belcher/electrum-personal-server#how-to

* Wallet methods are absolutely required for electrum personal server. It imports your electrum addresses into the bitcoin node and obtains transaction information that way.
