### ISSUE TITLE
Is it possible to use EPS with encryptwallet?

### ISSUE THREAD

**Issue by sunknudsen** [chris-belcher/electrum-personal-server#132]
If the Bitcoin Core server that EPS connects to isn’t encrypted using LUKS or equivalent, I am worried about having the master pub keys on it unencrypted (it exposes master pub keys which is the same as exposing the value of the holding). Is this vulnerability covered assuming I only connect to the server using SSH port forwarding?

**Comment by chris-belcher** [comment]
I don't know. Try it and if you can get it to work then let us know.

In general EPS should only be run on machines that you trust not to spy on you or lie to you.

**Comment by sunknudsen** [comment]
> Try it and if you can get it to work then let us know.

https://en.bitcoin.it/wiki/Wallet_encryption

> Wallet encryption uses AES-256-CBC to encrypt only the private keys that are held in a wallet.

Guess it’s not possible to encrypt the whole wallet using built-in features.

> In general EPS should only be run on machines that you trust not to spy on you or lie to you.

Totally agree, that’s why I am exploring sovereign alternatives such as Electrum + EPS. That being said, running a full node on a personal computer has drawbacks so I am exploring schemes using a server (that I would own and operate) for the full node and EPS as a proxy to Electrum. In this scheme, feels like it’s delicate to have master pub keys on the server from a privacy standpoint. Is there a way to avoid it?

**Comment by sunknudsen** [comment]
Given the master pub keys are added by EPS to the Bitcoin Core wallet, is it possible to list them and delete some of them on the server? What if I have the master pub keys of two Electrum wallets on to the server (added via EBS) and wish to remove the master pub keys of one of the wallets? Searched on DuckDuckGo for a while but didn’t find anything.

**Comment by chris-belcher** [comment]
> In this scheme, feels like it’s delicate to have master pub keys on the server from a privacy standpoint. Is there a way to avoid it?

No, the server must know what your bitcoin addresses are in order to be able to serve you wallet. Even if you somehow encrypted the mpks then the hosted server hardware would still be able to spy on you by eavesdropping on the connection between wallet and server.

> What if I have the master pub keys of two Electrum wallets on to the server (added via EBS) and wish to remove the master pub keys of one of the wallets?

You could remove them from the `config.ini` file, and then delete the Core wallet. Obviously if you do this you can't use that wallet anymore. Also a skilled technician with access to the server hardware could probably still recover those files (consider your threat model to decide whether this is something you're concerned with)

Maybe for your purposes you'd be better off obtaining a raspberry pi or similar hardware, running it in your own home and then installing EPS on that.

**Comment by sunknudsen** [comment]
> No, the server must know what your bitcoin addresses are in order to be able to serve you wallet. Even if you somehow encrypted the mpks then the hosted server hardware would still be able to spy on you by eavesdropping on the connection between wallet and server.

In the above scheme, the server would be self-hosted at home and connections to it would be done via SSH port forwarding so not worried about man-in-the-middle attacks.

> You could remove them from the config.ini file, and then delete the Core wallet. Obviously if you do this you can't use that wallet anymore. Also a skilled technician with access to the server hardware could probably still recover those files (consider your threat model to decide whether this is something you're concerned with)

That would work but was curious about solutions that would not break the other wallet.

Doing some research for a Bitcoin privacy story that I will publish on https://medium.com/@sunknudsen once I understand the space. Thanks for helping me connect a few dots.
