### ISSUE TITLE
Fee histogram breaks in recent versions of Bitcoin Core

### ISSUE THREAD

**Issue by alecalve** [chris-belcher/electrum-personal-server#134]
The issue lies here:

https://github.com/chris-belcher/electrum-personal-server/blob/015742ded02f1d35cbbb82fc8d04326bd62c9458/electrumpersonalserver/server/common.py#L298

The latest version of Bitcoin Core might not return "size" information for mempool entries if not specified explicitly.

See: https://github.com/bitcoin/bitcoin/blob/431d81b61ca968da2d7c25f0d56455a44cd46fed/src/rpc/blockchain.cpp#L429

One solution is to deactivate the fee histogram for recent Core users.

**Comment by chris-belcher** [comment]
Thanks for the issue.

It can be fixed by adding `deprecatedrpc=size` to bitcoin.conf

The PR https://github.com/chris-belcher/electrum-personal-server/pull/131 is the solution we're probably going to use.

**Comment by alecalve** [comment]
Ah, I didn't see that #131 addresses this issue already.
