### ISSUE TITLE
server.version returns a float, not a string

### ISSUE THREAD

**Issue by benma** [chris-belcher/electrum-personal-server#135]
The server.version should return two strings. 

Now it returns `["ElectrumPersonalServer 0.1.7", 1.2]` instead of `["ElectrumPersonalServer 0.1.7", "1.2"]` 

Electrum personal server used to do this:
https://github.com/chris-belcher/electrum-personal-server/blob/c9aa9f068e60/electrumpersonalserver/server/common.py#L249-L250

Relevant lines now:

https://github.com/chris-belcher/electrum-personal-server/blob/a2b37f91ed175d61ad1046262c4d8e4d6430da5a/electrumpersonalserver/server/common.py#L362-L363

**Comment by chris-belcher** [comment]
Thanks for the issue. I'll create a fix soon, it should be as simple as surrounding that value with str()

How did you even notice this?

**Comment by benma** [comment]
Thanks :)

> How did you even notice this?

A BitBox App user tried to connect with EPS and reported this error:

```
Failed to unmarshal response: ["ElectrumPersonalServer 0.1.7", 1.2]: Failed to unmarshal JSON: json: cannot unmarshal number into Go value of type string
```

I know it used to work in the past, so I looked at the file history.

(the client expects two strings, see https://github.com/digitalbitbox/bitbox-wallet-app/blob/43477e8fe7ebd08693270456998ecb82d63b4a66/backend/coins/btc/electrum/client/client.go#L133)

**Comment by chris-belcher** [comment]
I've pushed a commit https://github.com/chris-belcher/electrum-personal-server/commit/9bd9d7d013bdb0c5713939005d6e15d74693f42b which hopefully fixes this issue. Try it out when you get the chance to.

**Comment by benma** [comment]
Thanks. I will probably only get around to it in ~1.5 weeks, I'll post back here then.

**Comment by benma** [comment]
Tested and works. Thanks for the quick response!

**Comment by benma** [comment]
Unless I looked in the wrong place, it seems this has not made it into a release yet. Would you be willing to make a new release soon?

Cheers.
