### ISSUE TITLE
Unknown connections?

### ISSUE THREAD

**Issue by realSConway** [chris-belcher/electrum-personal-server#137]
Hi everyone. I hope you can assist with a few questions.
If wrong place, I will move, just let me know where.

running following code:

    ./electrum-personal-server ./electrum-personal-server/config.cfg

After displaying 3 addresses from master key:

    Obtaining bitcoin addresses to monitor . . .
    Obtained list of addresses to monitor in 378.3sec                                                 
    Building history with 4000 addresses . . .
    Found 24 txes. History built in 1.5sec                                                          
    Starting electrum server
    Listening for Electrum Wallet on ('127.0.0.1', 50002)                                                          
    Electrum connected from ('127.0.0.1', 54260)
    Found new tx: {'tx_hash': '#######', 'height': -1, 'fee': 188}
    Electrum wallet disconnected                     
    Electrum connected from ('127.0.0.1', 33768)

Where are  extra ports connection coming from?: 54260 and 33768?
What does found new tx with hight -1 mean? In Electrum it has yellow triangle with (!).

**Comment by DriftwoodPalace** [comment]
If you go to Tools > Network and change to the "server" tab in Electrum, what port is specified there?

If you have old transactions in the wallet or if something isn't showing correctly, you might need to do a rescan (with the rescan script) from a date before the first transaction was done for them to show up correct in Electrum.

**Comment by realSConway** [comment]
>If you go to Tools > Network and change to the "server" tab in Electrum, what port is specified there?
I actually have a ssh tunnel to my EPS.

    ssh -L 50002:localhost:50002 root@192.168.1.33

So my nework server settings are:
Localhost with port 50002

**Comment by realSConway** [comment]
RESOLVED.
>Where are extra ports connection coming from?: 54260 and 33768?

Extra connections were from external servers. (wasn't running electrum with oneserver=true)


>What does found new tx with hight -1 mean? In Electrum it has yellow triangle with (!).

I was sending tx from change addr that was not yet included in a block.

**Comment by chris-belcher** [comment]
> Extra connections were from external servers. (wasn't running electrum with oneserver=true)

This is not the explanation. Those port numbers you saw are the source ports. TCP packets have a source port and destination port. For EPS destination port is 50002 by default, but the source port can be anything and is chosen somewhat randomly.

**Comment by realSConway** [comment]
> > Extra connections were from external servers. (wasn't running electrum with oneserver=true)
> 
> This is not the explanation. Those port numbers you saw are the source ports. TCP packets have a source port and destination port. For EPS destination port is 50002 by default, but the source port can be anything and is chosen somewhat randomly.

Oh so it was actually my node or electrum client communicating with external servers? 

I guess my firewall settings are for inbound traffic only?:

    $ firewall-cmd --list-all
    public
      target: default
      icmp-block-inversion: no
      interfaces: 
      sources: 
      services: ssh dhcpv6-client bitcoin bitcoin-rpc tor-socks
      ports: 50002/tcp
      protocols: 
      masquerade: no
      forward-ports: 
      source-ports: 
      icmp-blocks: 
      rich rules:

**Comment by chris-belcher** [comment]
> Oh so it was actually my node or electrum client communicating with external servers?

No, the messages were about your Electrum communicating with Electrum Personal Server.

**Comment by realSConway** [comment]
yes

> > Oh so it was actually my node or electrum client communicating with external servers?
> 
> No, the messages were about your Electrum communicating with Electrum Personal Server.

Agreed, was just about to update my comment. The connections showed up after I started Electrum client. so that confirms that its the client connecting to external servers.

Last question, Electrum client is running on windows and my node (raspberry) is running bitcoind over tor only.
Are those outbound connections going via tor or clearnet?

**Comment by chris-belcher** [comment]
Which outbound connections?

**Comment by realSConway** [comment]
Ok, thanks for the link, very handy! 

One last question actually. I don't quite understand your comment in `config.ini_sample`

    #if you dont want to use the .cookie method with datadir, uncomment to config u/p here
    #rpc_user =
    #rpc_password =


I want to use RPC cookie authentication, how should `config.ini` look?

    rpc_user = USERNAME
    rpc_password = password_returned_from_rpcuser.py

Currently I have following appended to `config.ini` and it works to send tx, but is that correct?
`rpcauth=<USERNAME>:<SALT>$<HASH>`

**Comment by chris-belcher** [comment]
If you want to use the RPC auth cookie then leave the `rpc_user` and `rpc_password` lines commented (i.e. starting with `#`)

**Comment by realSConway** [comment]
Understood.
Thank you for your time.
