### ISSUE TITLE
Change Addresses aren't tracked

### ISSUE THREAD

**Issue by MaDeRkAn** [chris-belcher/electrum-personal-server#140]
I'm not sure but I think EPS just creates addresses from path "m/0". But Electrum uses also "m/1" for change addresses. EPS does not insert these change addresses to the core that's why we don't get any information about them.

EPS should create and add change addresses default count is 7 by electrum but it should be configurable by EPS.

**Comment by chris-belcher** [comment]
Thanks for the issue. What did you see/do which made you believe that they aren't tracked?

**Comment by MaDeRkAn** [comment]
I was using my multi signature watch only wallet with electrum with public servers. I have changed it to EPS. 
I had 14 transactions but EPS found 11 transactions. Then I have checked these 3 transactions. Their inputs include just change addresses. After that, I checked my changed addresses on bitcoin core they are not there. All "m/0" is there but not any "m/1".

**Comment by chris-belcher** [comment]
That's really strange. The "m/1" path is definitely calculated and added. Maybe you accidently hit ctrl+c when EPS was importing addresses into core, which would mean EPS didn't import all addresses it should've. I think if you tried starting everything again from the beginning with a new empty wallet.dat file in Core then it would import those addresses and the transaction should show up.

**Comment by MaDeRkAn** [comment]
Yes you are right. But I have added 10k addresses it took more than 1 hour. Do we have any chance to increase speed of this ? Or is it limited by Bitcoin Core ?

**Comment by chris-belcher** [comment]
It's limited by the pure python ECC code, there is an issue about it #112.
