### ISSUE TITLE
Green check mark vs computer icon.

### ISSUE THREAD

**Issue by bar17** [chris-belcher/electrum-personal-server#141]
Hello, I am trying to decipher the difference between the green check mark and the computer icon in the electrum GUI when using EPS.

I am using Windows, Bitcoin Core 018.0, EPS 0.17, Electrum 3.3.6. I have set up the software per the tutorial [https://github.com/DriftwoodPalace/guides/blob/master/hodl-guide/hodl-guide_63_eps-win.md](https://github.com/DriftwoodPalace/guides/blob/master/hodl-guide/hodl-guide_63_eps-win.md) and have electrum only connecting to one node, "localhost".

I have successfully verified incoming and outgoing UTXOs on several wallets and have not figured out why sometimes a green checkmark is present and why sometimes a computer icon is present. When the computer icon is present the "date" field filled with "Local" instead of a date.

At some point in the past the circle at the bottom was blue as well and all icons were computers instead of green  check marks. However, now most wallets have all green check marks and only a few have computer icons. The circle is green in all wallets.

The behavior seemed to change as I was troubleshooting and rescaning and probably connected a few times to non localhost servers over electrum because of accidentally not using the shortcut that forces "--oneserver --server localhost:50002:s"

I wish I could be more specific with respect to reproducing a computer icon or blue circle in contrast to green checkmark and green circle but I was doing multiple things before I realized the change in Electrum behavior.

Any insight is appreciated. Thank you.

**Comment by chris-belcher** [comment]
Thanks for the issue. This happened to me once but I wasn't able to reproduce the issue. I'd say try setting up EPS again from the start with a new Core wallet.dat file, then import all addresses again and rescan. Also restore your Electrum wallet again from seed. (Remember you can export and import labels so you don't lose them)

Blue circle in the bottom-right means Electrum was connecting to the server(s) over Tor.

**Comment by bar17** [comment]
Creating a new Core wallet.dat, importing and rescanning /w EPS again  worked. All dots are green. Thank you.
