### ISSUE TITLE
Multi-signature wallet

### ISSUE THREAD

**Issue by freddiemacd** [chris-belcher/electrum-personal-server#142]
I would like to use this with a multi-signature wallet.  If I read through the documetation correctly, I need to know the master public key.  How do I find out the master public key for a multisig wallet?  In electrum, Under Wallet>Information, I see the individual seed master public keys but not the one for the multi-signature wallet.

**Comment by chris-belcher** [comment]
Multisig wallets in Electrum have more than one master public key. In the sample config file there is an example for how to add multisig wallets using their individual MPKs: https://github.com/chris-belcher/electrum-personal-server/blob/master/config.ini_sample#L19

**Comment by freddiemacd** [comment]
Thank you for the info.

**Comment by merland** [comment]
@freddiemacd  
This feature was recently added to my project merland/seedpicker. Please try it out to see if it covers your needs:
[http://seedpicker.net/calculator/last-word.html](http://seedpicker.net/calculator/last-word.html)
Any feedback is greatly appreciated.
