### ISSUE TITLE
Help with Mac OS Mojave

### ISSUE THREAD

**Issue by Silver-Fox** [chris-belcher/electrum-personal-server#143]
I followed the instructions [here](https://github.com/DriftwoodPalace/guides/blob/master/hodl-guide/hodl-guide_64_eps-mac.md), buth when I start EPS I get this error message:

```
usage: electrum-personal-server [-h] [--rescan] [-v] config_file
electrum-personal-server: error: unrecognized arguments: Personal Server/electrum-personal-server-electrum-personal-server-v0.1.7/config.cfg
```

I've double checked my `config.cfg` file but can't see anything wrong with it.

**Comment by chris-belcher** [comment]
Try surrounding the path to the config file with `"` marks (quotes)

e.g. `electrum-personal-server "path/to/config.cfg"

**Comment by Silver-Fox** [comment]
Thanks. I did what you said and EPS now appears to start correctly.

However, when I then create the script to start Electrum set to [disable connections to other servers](https://github.com/DriftwoodPalace/guides/blob/master/hodl-guide/hodl-guide_64_eps-mac.md#disable-connections-to-other-servers), I get the following output:

`The file /Users/**********/wallet/Electrum.app does not exist.`

I've double checked that I'm using the correct path to the Electrum app in my Electrum start up script.

**Comment by Silver-Fox** [comment]
Thanks. I did what you said and EPS now appears to start correctly.
