### ISSUE TITLE
issue with spesmilo/electrum used with this

### ISSUE THREAD

**Issue by bill-walker** [chris-belcher/electrum-personal-server#15]
https://github.com/spesmilo/electrum/compare/master...bill-walker:master

i fixed electrum to work with electrum-personal-server and be idiot proof. not even possible to leak addresses by mistake. (as long as noob doesn't put a public electrum server in there.)

anyone want to review my hacks?

**Comment by bill-walker** [comment]
I plan to keep it updated even with spesmilo/electrum going forward.

**Comment by chris-belcher** [comment]
Looks promising. Could you squish all those commits into one? That would make it easier to review.

**Comment by bill-walker** [comment]
how do I do that on cli without wiping out the repository? I moved the changes to the 3.1 branch, and it's easy to review the changes with the gui, with https://github.com/spesmilo/electrum/compare/3.1...bill-walker:3.1

**Comment by bill-walker** [comment]
also I don't know how to base changes from a tag, specifically the 3.1.2 tag.

**Comment by bill-walker** [comment]
can you link me to some good git tutorials? I don't know git yet.

**Comment by chris-belcher** [comment]
Here's a tutorial for squishing commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by bill-walker** [comment]
i just screwed it up worse. can i give you access to the repo?

**Comment by bill-walker** [comment]
https://github.com/bill-walker/electrum/tree/3.1.2-personal

https://github.com/spesmilo/electrum/compare/3.1.2...bill-walker:3.1.2-personal

here it is as a branch, chris. best i could do, aside from remembering how i fixed kivy, and changing the title bar.

**Comment by bill-walker** [comment]
i'd like to get this working with pip eventually. for now, it's safer for people to diff the code and clone the branch manually.

**Comment by bill-walker** [comment]
https://github.com/bill-walker/electrum/blob/master/README.rst

electrum --server 127.0.0.1:50002:s --oneserver --dir /home/user/.electrum-personal

Chris, this can all be done on the CLI. I wasted my time, more or less. Learned about the electrum codebase at least.

**Comment by chris-belcher** [comment]
You also learned about git!
