### ISSUE TITLE
Loading multiple zpub master keys?

### ISSUE THREAD

**Issue by cidadededeus36** [chris-belcher/electrum-personal-server#151]
i tried adding two zpub keys to my config file, but eps doesn't seem to like it when I add multiple zpub keys. If i have a mix of xpubs/ypubs/zpubs added to my config, it will display and import the xpub/ypub normally, but will only import the first zpub added. Any master key added after the first zpub is omitted regardless if format is xpub ypub or zpub.

**Comment by chris-belcher** [comment]
Thanks for the bug report, I'll try to reproduce this.

**Comment by chris-belcher** [comment]
I wasn't able to reproduce this. It also doesn't really make sense from the code.

Closing the issue now but if you see this can you paste here your `config.ini` with the private information like master public keys removed.
