### ISSUE TITLE
In README.md, local/bin should be .local/bin

### ISSUE THREAD

**Issue by sumBTC** [chris-belcher/electrum-personal-server#165]
> 1. Make sure `~/local/bin` is in your $PATH 

In README.md should be: 

1. Make sure `~/.local/bin` is in your $PATH

**Comment by chris-belcher** [comment]
Thanks. Fixed https://github.com/chris-belcher/electrum-personal-server/commit/6b8adab72ce32e7a870a89532c3550b33ef6c943
