### ISSUE TITLE
Guide for install on MacOS (link upgrade)

### ISSUE THREAD

**Issue by Pindol83** [chris-belcher/electrum-personal-server#166]
Hi Chris,

please upgrade the link for install EPS on MacOs in your main page, the new link is this: https://github.com/DriftwoodPalace/Hodl-Guide/blob/master/hodl-guide_64_eps-mac.md

I would like to upgrade from eps 1.6.0 to the new version 2.0.0, can i simply replace the new file for upgrade it, without install eps again?

thanks

**Comment by chris-belcher** [comment]
Thanks. I've done that here https://github.com/chris-belcher/electrum-personal-server/commit/3204a693926cbaf9fe7811bcce2add9bc246a60b

For upgrading, you first have to uninstall the old version with something like `pip3 uninstall electrum-personal-server`. Then download the new version and as usual use something like `pip3 install --user .` (see one of the guides or the README)

**Comment by DriftwoodPalace** [comment]
Sorry Chris, I moved it again (created a pull request). Hopefully for the last time. I'll try to update the guide with your instructions above. I'll add a link to the new guide in the old guide as well.
