### ISSUE TITLE
Wallet electrumpersonalserver already exists

### ISSUE THREAD

**Issue by McMurdo2009** [chris-belcher/electrum-personal-server#168]
When I run:
bitcoin-cli createwallet electrumpersonalserver true

I get the message:
Wallet electrumpersonalserver already exists.

But when I do bitcoin-cli listwallets, I get:
[
"",
"1"
]

...no wallet named "electrumpersonalserver."

then when I do bitcoin do bitcoin-cli -rpcwallet="1" listunspent, 100% of the UTXOs are labeled "electrum-watchonly-addresses", (which made me think it was the wallet created by "bitcoin-cli createwallet electrumpersonalserver true".

However when I do bitcoin-cli -rpcwallet="1" getwallet info, I see that "private_keys_enable" = True, and the wallet we created should have that disabled.

Also: when I do listunspent for each wallet, I've find a UTXO that appears in both of them.

Thoughts?

**Comment by chris-belcher** [comment]
Seems pretty weird to me. IDK.

**Comment by McMurdo2009** [comment]
Interesting development: 

the folder "electrumpersonalserver" does exist at /home/user/.bitcoin/testnet3/wallets/, but it just doesn't get listed when I do: bitcoin-cli listwallets.

I also did: bitcoin-cli createwallet arbitrary_wallet_name, and that also doesn't show up when I do: bitcoin-cli listwallets, but a folder was also created for it in /home/user/.bitcoin/testnet3/wallets/

I guess the next thing to do is take this to bitcoin stack exchange. Would it be proper form to leave this EPS issue open or close it?

**Comment by chris-belcher** [comment]
Leave the issue open until its solved, and perhaps link your stackexchange thread here

**Comment by jmacxx** [comment]
You probably solved this already, in which case this issue should be closed, but anyway `listwallets` only lists the wallets that have been loaded.  `loadwallet [walletname]` is the command to load a wallet after creating it.  `loadwallet` needs to be called again whenever bitcoin core is restarted.

https://chainquery.com/bitcoin-cli#wallet

**Comment by shesek** [comment]
You might want to add `wallet=<name>` to your `bitcoin.conf` so it'll automatically be loaded on startup.
