### ISSUE TITLE
Problem at "pip3 install --user" step

### ISSUE THREAD

**Issue by inpharmaticist** [chris-belcher/electrum-personal-server#180]
I get 
>You must give at least one requirement to install (see "pip help install")

"pip3 help install" yields under "--user"
>Install to the Python user install directory for your platform. Typically ~/.local/, or APPDATA%\Python on Windows. (See the Python documentation for site.USER_BASE for full details.)  On Debian systems, this is the default when running outside of a virtual environment and not as root.

I typed "pip3 install --user ~/.local/" and got
>Directory '/home/corey/.local/' is not installable. File 'setup.py' not found.

Am I missing something?

**Comment by inpharmaticist** [comment]
On linux Mint

**Comment by chris-belcher** [comment]
try `pip3 install --user /path/to/eps/directory`

**Comment by inpharmaticist** [comment]
Fixed. Needed to include the period. I also had to add setuptools
>sudo apt-get install -y python3-setuptools
