### ISSUE TITLE
Add Linux tar file for 0.2 release

### ISSUE THREAD

**Issue by the-metalworker** [chris-belcher/electrum-personal-server#182]
Hello I am trying to install EPS on a Linux server but the latest 0.2 release only has the .zip file for Windows not the .tar.gz for Linux. Can you @chris-belcher please upload the tar and the signature file for the tar? cheers

**Comment by chris-belcher** [comment]
I think the tar file and signature is there:

https://github.com/chris-belcher/electrum-personal-server/archive/eps-v0.2.0.tar.gz

https://github.com/chris-belcher/electrum-personal-server/releases/download/eps-v0.2.0/eps-v0.2.0.tar.gz.asc
