### ISSUE TITLE
I can't install the Electrum personal server

### ISSUE THREAD

**Issue by jonjonez** [chris-belcher/electrum-personal-server#184]
I'm following everything according to the readme.md tutorial, I execute the command: pip3 install --user. but there is an error in the terminal and I don't know what to do.
![image](https://user-images.githubusercontent.com/23480437/76132592-705ba500-5ff2-11ea-8bbb-3c1d09673f01.png)
I already managed to install EPS the last time, but I had to format the computer and installed another linux (mint), why don't you want to go now?

![image](https://user-images.githubusercontent.com/23480437/76132603-7fdaee00-5ff2-11ea-8650-de812df35158.png)

I can't install it anyway, try to do it anyway

**Comment by chris-belcher** [comment]
Try following this? https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools I found the link searching
