### ISSUE TITLE
No signed data in eps-v0.2.0.tar.gz.asc

### ISSUE THREAD

**Issue by jodobear** [chris-belcher/electrum-personal-server#185]
While trying to verify signatures, i get the following error. How is this possible.. am i doing something wrong?

OS: Linux Mint 19
Command: `gpg --verify eps-v0.2.0.tar.gz.asc`
Error: 
`gpg: no signed data
gpg: can't hash datafile: No data`

**Comment by chris-belcher** [comment]
The correct command is:

`gpg --verify SIGNATURE-FILE.asc ACTUAL-FILE`
