### ISSUE TITLE
Electrum server host - connections

### ISSUE THREAD

**Issue by Mentakh** [chris-belcher/electrum-personal-server#19]
Hello

I wanted to connect my computer with my Electrum Wallet to my computer with my Bitcoin Core and Electrum Personal Server.
I tried to specify my IP address, but could only choose between : localhost and 0.0.0.0
Being able to specify a LAN IP address would be a usefull feature imho.

**Comment by chris-belcher** [comment]
I'm not exactly sure what you mean. Are you talking about editing `config.cfg` to change `host` in `[electrum-server]` ? I believe you could set that to be the IP address of your Electrum Wallet computer and then Electrum Personal Server would only accept connections from that.

I haven't tested that though, so if you've already done that and it doesn't work then IDK. That host and port just get passed to socket.bind()

**Comment by Mentakh** [comment]
Yes, I edited the config.cfg and changed the host in [electrum-server]
When set to 0.0.0.0 it works, but when I set the host to the IP address from my Electrum Wallet computer I get the following error : "OSError: [WinError 10049] The requested address is not valid in its context"
The IP address is correct, the Electrum Personal Server log confirms this.
So my guess is that there is some sort of hard coded limit to 0.0.0.0 and 127.0.0.1 ...
I have it covered by my hardware firewall, but still ... this is a needed feature imho.
I will look into it further and see if I can make something of it.

**Comment by Mentakh** [comment]
Looks like it is expected behavior in Python. It needs to bind to a local address. For now I have changed my windows firewall rule so that it only allows Python connections from the specified IP address.

**Comment by chris-belcher** [comment]
> Looks like it is expected behavior in Python.

Is that right? Sucks if true.

I just saw on the [raspberry pi guide](https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_64_electrum.md) that he also does it by binding to 0.0.0.0 and then using the firewall to control access.

I could add a whitelisting address feature where after `server_socket.accept()` returns with a socket, that socket's IP address is checked and if it isn't in the whitelist then `close()` is called.

**Comment by chris-belcher** [comment]
Whitelisting feature added https://github.com/chris-belcher/electrum-personal-server/commit/5a255e406a578622f074259ece66e9d047d8ac98

**Comment by Mentakh** [comment]
Agreed, use on your private and secured LAN.
The feature looks good. Going to test it in the weekend.

**Comment by Mentakh** [comment]
Hey, it took a bit longer to test it, but it is working fine, so thanks for the work.
