### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by amirelayyan** [chris-belcher/electrum-personal-server#193]
When running `electrum-personal-server config.ini`

I get: `ERROR: Error with bitcoin json-rpc: JsonRpcConnectionError ('authentication for JSON-RPC failed')`

Both `rpc_user` and `rpc_password` are typed identically to the ones in the config.ini file. Could someone assist with this issue ?

**Comment by chris-belcher** [comment]
Make sure your Bitcoin Core is correctly reading the `bitcoin.conf` file. Try adding `connect=0` to the file and seeing whether Core indeed doesnt connect to any other peer.

**Comment by amirelayyan** [comment]
When I run `bitcoin-qt -server` and `bitcoind` everything seems to be running correctly

**Comment by chris-belcher** [comment]
That means it's not reading the file `bitcoin.conf`, so you need to fiddle around making it load. Perhaps moving the file to the right place or using the `-datadir=` command line argument.
