### ISSUE TITLE
can I just get the zip file?

### ISSUE THREAD

**Issue by nybe** [chris-belcher/electrum-personal-server#196]
I go through this every time I try to install a new version of EPS... 

Can I just get: "eps-v0.2.1.zip" without the ".asc" at the end? 

It NEVER verifies properly on Mac 

EDIT: I'm a dope. figured it out.

**Comment by chris-belcher** [comment]
For any lurkers who read this, you go here https://github.com/chris-belcher/electrum-personal-server/releases/tag/eps-v0.2.1

And then click `Source code (zip)` or `Source code (tar)`.

**Comment by chris-belcher** [comment]
Also there is this tutorial for MacOS which might help https://driftwoodpalace.github.io/Hodl-Guide/hodl-guide_64_eps-mac.html
