### ISSUE TITLE
EPS Crashes When Electrum Client Attempts to Connect

### ISSUE THREAD

**Issue by Linrono** [chris-belcher/electrum-personal-server#198]
I am having an issue with EPS.
I tried searching for this issue, but I'm afraid I am not sure what the issue is exactly.
I can start EPS without issue, but when I connect with my electrum client, EPS crashes.
I get this output:

`INFO:2020-06-08 00:27:01,436: Obtaining bitcoin addresses to monitor . . .
INFO:2020-06-08 00:27:01,877: Obtained list of addresses to monitor in 0.4498879909515381sec
INFO:2020-06-08 00:27:01,877: Building history with 2000 addresses . . .
INFO:2020-06-08 00:27:01,895: Found 9 txes. History built in 0.01756453514099121sec
INFO:2020-06-08 00:27:01,895: Listening for Electrum Wallet on ('127.0.0.1', 50002)

If this project is valuable to you please consider donating:
	bc1qwt8kh83dpdj4yuquvsf28rhcft2rjh6jvy6678
Traceback (most recent call last):
  File "/usr/bin/electrum-personal-server", line 11, in <module>
    load_entry_point('electrum-personal-server==0.2.0.dev0', 'console_scripts', 'electrum-personal-server')()
  File "/usr/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 460, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/usr/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 120, in run_electrum_server
    sock = ssl.wrap_socket(sock, server_side=True,
  File "/usr/lib/python3.8/ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
`
It looks like an issue with ssl. I have openssl installed on my machine currently. Maybe it's just a dependency issue, I don't know.
I am running Linux BTW. Electrum 3.3.8.

**Comment by jmacxx** [comment]
I'm also experiencing the issue using latest eps release (0.2.1) / bitcoind 0.20.0 / Odroid-UX4.  

Same as  https://github.com/chris-belcher/electrum-personal-server/issues/197#issuecomment-639627011
