### ISSUE TITLE
My node is not confirming my transactions

### ISSUE THREAD

**Issue by miguelmartinn9** [chris-belcher/electrum-personal-server#199]
I don't know if this belongs here, but I didn't know where to ask.

I finally connected my hardware wallet to Electrum (through EPS) which I then connected to my node.

When I connect to an external node, it gets the green check saying that it's confirmed, but when I'm using my node, this appears in all transactions:

![image](https://user-images.githubusercontent.com/39597568/84035450-06112280-a99c-11ea-80ca-253788ea214e.png)

This are my Electrum network settings:
![image](https://user-images.githubusercontent.com/39597568/84035483-188b5c00-a99c-11ea-9d5a-aef4e223936c.png)

This is what the console says (I'm connected through Electrum Personal Server)
![image](https://user-images.githubusercontent.com/39597568/84035491-1e813d00-a99c-11ea-8cdb-3f0412931527.png)

Am I missing something? Thanks!

**Comment by miguelmartinn9** [comment]
Plus, I just broadcasted a transaction without problems, so the only thing that my node doesn't do is confirm the transactions. I don't know why

**Comment by chris-belcher** [comment]
Thanks for the issue.

Which version of EPS are you using?

One possibility is that some of your addresses have not been imported correctly. To check for that take one of your addresses from a transaction there and run the Bitcoin Core RPC call `getaddressinfo <youraddress>`. You can do that either on the command line like `bitcoin-cli getaddressinfo <youraddress>` or if you use bitcoin-qt then in the Console. You should see information indicating that the address has been imported into the Core wallet, if not then try increasing the value of `initial_import_count` in the EPS `config.ini` file.

**Comment by miguelmartinn9** [comment]
Hi, I'm running EPS 0.2.0
When I run bitcoin-cli getaddressinfo <my address> I get nothing relevant. How can I check if it has been imported into the Core wallet?

**Comment by miguelmartinn9** [comment]
I think the problem is that I forgot to put the master keys in the config file.

**Comment by miguelmartinn9** [comment]
Yup, that was it. Thanks a lot!

**Comment by chris-belcher** [comment]
EPS will exit with an error if there are no addresses to track, why did that not happen?
