### ISSUE TITLE
looking for .cookie file

### ISSUE THREAD

**Issue by 0xbytes** [chris-belcher/electrum-personal-server#2]
running python3 server.py gives

11:54:27,417584 [  LOG] Unable to find .cookie file, try setting `datadir` config

my .bitcoin directory does not have .cookie file. 
if it helps, my bitcoin.conf file:
zmqpubrawblock=tcp://127.0.0.1:8501
zmqpubrawtx=tcp://127.0.0.1:8501
server=1
daemon=1
dbcache=150
rpcuser=*******
rpcpassword=*******
rpcport=8332
rpcallowip=127.0.0.1
rpcthreads=10
port=6667
bind=127.0.0.1:6667
#disablewallet=1
#checklevel=1
#minrelaytxfee=0.000001
limitfreerelay=6
txindex=1
maxconnections=60

**Comment by chris-belcher** [comment]
Delete rpcuser and rpcpassword from your bitcoin.conf file. If these options exist then bitcoind doesn't create a cookie file.

**Comment by Stadicus** [comment]
I am hanging on the same issue. Problem is that most other services (Lightning nodes LND or eclair) require the rpcuser / rpcpass authentication. 

Is it possible to use both cookie & rpcuser/pw at the same time?

**Comment by chris-belcher** [comment]
It isnt.. so I'll recode it to support both methods.

**Comment by chris-belcher** [comment]
I just pushed this commit to add that option.

https://github.com/chris-belcher/electrum-personal-server/commit/478fc02820696bdbbf5af9e7ca9b1a6c4a6f954a

**Comment by 0xbytes** [comment]
I cannot delete rpcuser nor rpcpass because I am using lightning that requires it.

**Comment by chris-belcher** [comment]
Then update to the latest commit and set rpc_username/password in the config.cfg file.

**Comment by Stadicus** [comment]
Wow, that's fast. Just went for dinner, and you already implemented it? Thanks!

**Comment by 0xbytes** [comment]
looks like this issue is solved.

**Comment by toxicacd** [comment]
The rescan script still wants a cookie.

**Comment by DaReaper** [comment]
I get 22:21:08,043295 [  LOG] Error with bitcoin rpc, check host/port/user/password after configuring the config.cfg file with the rpc user and password as in my Bitcoin core config. I've verified multiple times that the user and password are same.

**Comment by Stadicus** [comment]
Unfortunately, it's not working that smoothly for me. I run Bitcoin Core v0.16.0, fully archiving, with transaction index. But without wallet, is this maybe an issue? Also, the user `bitcoin` does not have `sudo` privileges.

The config is as standard as it gets, but entered 

* an xpub key: `stadicus = xpub##################abc7` 
* rpc_user = ###########
* rpc_password = ###########

```
bitcoin@RaspiBolt:~/electrum-personal-server $ bitcoind --version
Bitcoin Core Daemon version v0.16.0

bitcoin@RaspiBolt:~/electrum-personal-server $ bitcoin-cli --getinfo
{
  "version": 160000,
  "protocolversion": 70015,
  "walletversion": null,
  "balance": null,
  "blocks": 515709,
  "timeoffset": 0,
  "connections": 38,
  ...
  "testnet": false,
  ...
  "warnings": ""
}

bitcoin@RaspiBolt:~/electrum-personal-server $ cat ~/.bitcoin/bitcoin.conf
# RaspiBolt LND Mainnet: bitcoind configuration

# Bitcoind options
server=1
daemon=1
txindex=1
disablewallet=1

# Connection settings
rpcuser=###########
rpcpassword=###########
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000

# Raspberry Pi optimizations
dbcache=100
maxorphantx=10
maxmempool=50
maxconnections=40
maxuploadtarget=5000

bitcoin@RaspiBolt:~/electrum-personal-server $ netstat -nap|grep bitcoin|grep LISTEN
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:29000         0.0.0.0:*               LISTEN      621/bitcoind
tcp        0      0 127.0.0.1:8332          0.0.0.0:*               LISTEN      621/bitcoind
tcp        0      0 0.0.0.0:8333            0.0.0.0:*               LISTEN      621/bitcoind
tcp6       0      0 ::1:8332                :::*                    LISTEN      621/bitcoind
tcp6       0      0 :::8333                 :::*                    LISTEN      621/bitcoind

bitcoin@RaspiBolt:~/electrum-personal-server $ ./server.py
Traceback (most recent call last):
  File "./server.py", line 462, in <module>
    main()
  File "./server.py", line 437, in main
    get_scriptpubkeys_to_monitor(rpc, config)
  File "./server.py", line 307, in get_scriptpubkeys_to_monitor
    [transactionmonitor.ADDRESSES_LABEL]))
  File "/home/bitcoin/electrum-personal-server/electrumpersonalserver/jsonrpc.py", line 62, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'message': 'Method not found', 'code': -32601}
```

**Comment by DaReaper** [comment]
@chris-belcher Yesh I see the following in the debug log:
22:52:51,340711 [DEBUG] obtaining auth from rpc_user/pass
22:52:51,343119 [  LOG] Error with bitcoin rpc, check host/port/user/password

**Comment by toxicacd** [comment]
@chris-belcher Wow, you are fast! Working like a charm now here (Win10, bitcoin 0.16.0). I am very impressed - thank you!

**Comment by chris-belcher** [comment]
@DaReaper Update to this latest commit and try again https://github.com/chris-belcher/electrum-personal-server/commit/4a0f7338d62a287fc76910be144270c0dc46683a

That commit makes that error message have more detail, which should hopefully provide more clues.

**Comment by DaReaper** [comment]
@chris-belcher Thanks, I've updated to the latest commit. Here's the detailed log now:

23:12:45,498660 [DEBUG] obtaining auth from rpc_user/pass
23:12:45,517053 [  LOG] Error: JsonRpcConnectionError("JSON-RPC connection failed. Err:ConnectionRefusedError(111, 'Connection refused')",)
23:12:45,517108 [  LOG] Error with bitcoin rpc, check host/port/user/password

**Comment by chris-belcher** [comment]
So any idea why it says Connection refused? Is Bitcoin Core definitely switched on. IDK.

**Comment by Stadicus** [comment]
Connection working, rescan in progress. Thanks!

**Comment by DaReaper** [comment]
@chris-belcher Yes, I have Bitcoin-qt (core) running with 8 outgoing and 2 incoming connections. 

I've also added to my bitcoin.conf:

rpcallowip=127.0.0.1
rpcport=8332

I'm running bitcoin core as a tor node, I'm not sure if that would affect it by any means.

**Comment by chris-belcher** [comment]
Maybe try `netstat -l` to see if Core is definitely has the rpc port open (8332 by default).

I'm sure you already have, but bitcoin.conf needs to have server=1 as well.

**Comment by chris-belcher** [comment]
Cool. Thanks for testing.

Let me know if you all get to the point of actually connecting Electrum to it after you rescan. If there's no other problems I'll make a new minor release with all the little edits I just did.

**Comment by chris-belcher** [comment]
Good to hear.

Electrum recently introduced varying version bytes for master public keys which indicates what kind of wallet is created. ypub indicates p2wpkh-p2sh. A full list is here: https://github.com/spesmilo/electrum-docs/blob/master/xpub_version_bytes.rst

TYVM for the donation, it will be put to good use.

**Comment by chris-belcher** [comment]
I tagged a new release which includes the bug fixes from this issue. Closing it now.
