### ISSUE TITLE
Improve error message if wallet feature is disabled

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#20]
If `bitcoind` is compiled with `--disable-wallet` or launched with `-disablewallet=1` the server throws a generic RPC error, suggesting there is a username and password problem.

**Comment by chris-belcher** [comment]
Made error message more general here https://github.com/chris-belcher/electrum-personal-server/commit/4dc8422e6e18ef09e771aed53b7a334c9d376d2e
