### ISSUE TITLE
Can't get EPS to work on multiple wallets

### ISSUE THREAD

**Issue by miguelmartinn9** [chris-belcher/electrum-personal-server#201]
The first time I configured EPS on my node I successfully connected it to one of my wallets. But when I tried to do so, with the rest of them, I get stuck on:

```
INFO:2020-06-09 13:23:52,938: Starting Electrum Personal Server
INFO:2020-06-09 13:23:52,939: Logging to /tmp/electrumpersonalserver.log
INFO:2020-06-09 13:23:53,793: Displaying first 3 addresses of each master public key:
INFO:2020-06-09 13:23:54,019: 
samourai_1 =>
	bc1
	bc1
	bc1
INFO:2020-06-09 13:23:54,313: 
wallet_1 =>
	bc1
	bc1
	bc1
INFO:2020-06-09 13:23:54,617: 
wallet_2 =>
	bc1
	bc1
	bc1
INFO:2020-06-09 13:23:54,915: 
wallet_3 =>
	bc1
	bc1
	bc1
INFO:2020-06-09 13:23:54,988: Obtaining bitcoin addresses to monitor . . .
```

Is there anything else I have to add to the config file to make it work? (Apart from adding the master public keys)

**Comment by chris-belcher** [comment]
Just wait.

On another issue you said you're using EPS version 0.2.0, which has the very slow address generation (see issue #112). So just wait for the addresses to be generated.

**Comment by miguelmartinn9** [comment]
Yup, I had to wait. Sorry for opening so many issues.
