### ISSUE TITLE
eps 0.2.1.1 doesn't start / Win10 / Bitcoin Core 0.2

### ISSUE THREAD

**Issue by 91237665** [chris-belcher/electrum-personal-server#204]
It is the first time I installed eps, and it doesn't start: after "starting electrum server" the command window automatically closes and there is no server on '127.0.0.1', 50002: 

INFO:2020-06-21 14:34:36,792: Starting Electrum Personal Server 0.2.1.1
INFO:2020-06-21 14:34:36,793: Logging to C:\Temp/electrumpersonalserver.log
DEBUG:2020-06-21 14:34:36,794: Process ID (PID) = 1120
DEBUG:2020-06-21 14:34:36,794: obtaining auth from rpc_user/pass
DEBUG:2020-06-21 14:34:36,815: Checking whether rescan is in progress
INFO:2020-06-21 14:34:36,825: Displaying first 3 addresses of each master public key:
INFO:2020-06-21 14:34:36,827: 
wallet =>
	bc1...
	bc1...
	bc1...
INFO:2020-06-21 14:34:36,827: Obtaining bitcoin addresses to monitor . . .
INFO:2020-06-21 14:34:37,466: Obtained list of addresses to monitor in 0.6494321823120117sec
INFO:2020-06-21 14:34:37,466: Building history with 2000 addresses . . .
DEBUG:2020-06-21 14:34:37,475: listtransactions skip=0 len(ret)=0
DEBUG:2020-06-21 14:34:37,478: unconfirmed_txes = defaultdict(<class 'list'>, {})
DEBUG:2020-06-21 14:34:37,478: reorganizable_txes = []
DEBUG:2020-06-21 14:34:37,478: last_known_wallet_txid = None
INFO:2020-06-21 14:34:37,478: Found 0 txes. History built in 0.012695789337158203sec
DEBUG:2020-06-21 14:34:37,478: Starting electrum server

**Comment by chris-belcher** [comment]
Is that the debug log file which you've pasted? I bet there's a stack trace which just isn't being written to the debug log file.

Could you do this:
* Open the windows command prompt and use `cd` to go to the folder where EPS and its config file are.
* Type `electrum-personal-server config.ini` and press enter, replacing `config.ini` with the name of your config file if its called something different.
* You should get the same error along with a stack trace, copypaste it here (or take a screenshot)

**Comment by 91237665** [comment]
Funny! This way it works! Thank you! Can be closed:)

But it doesn't work if I try to open config.ini with choosing it and then "open with" directly in win10 -> same behavior I wrote above

**Comment by chris-belcher** [comment]
@91237665 could you explain a bit more? Even though your problem is solved the same problem might be encountered by other users.

Can you briefly explain step-by-step how you use "open with" to run electrum personal server on windows10 ?

**Comment by 91237665** [comment]
I found out today, that if I use drag & drop ini to exe in windows explorer, it works fine.
but, look at the image, if I choose config.ini and choose to open it with electrum-personal-server.exe -> then exe stated execute ini, but the command window automatically closes and server doesn't start.

I hope I could explain it better this time :) Thanks for your work!
![for_chris](https://user-images.githubusercontent.com/67239854/85430817-ecb5cc00-b580-11ea-8f25-a5e1227ab888.jpg)

**Comment by chris-belcher** [comment]
I understand. Thanks for the explanation.

Yes the way you were doing it doesn't work. The only two ways are 1) dragging, and 2) use the command prompt.

However I'm surprised that you way using "open with" worked a little bit, so I might play around with it a little bit, perhaps it can be made to work too, and would provide a third way.
