### ISSUE TITLE
error while running electrum-personal-server config.ini

### ISSUE THREAD

**Issue by xpsx** [chris-belcher/electrum-personal-server#205]
hello, 

i receive this error when i run the code:
![image](https://i.ibb.co/CQpmTF7/Schermata-2020-07-14-alle-12-09-02.png)

**Comment by xpsx** [comment]
and if i enter walletpassphrase in the config.ini it gives me this error:
![image](https://i.ibb.co/5xfSYPN/Schermata-2020-07-14-alle-12-30-25.png)

**Comment by chris-belcher** [comment]
Firstly, your censoring of your bitcoin addresses isn't good enough and it's still possible to figure out what those 3 addresses are. You need to blank out the whole address (ideally you'd create a brand new wallet now)

To solve the wallet encryption error you should create a brand new Bitcoin Core wallet file, here is the relevant part from the README: `On first run, it is recommended to create a wallet dedicated to Electrum Personal Server using the command line argument bitcoin-cli createwallet electrumpersonalserver true.`. You could also check one of the [install guides](https://github.com/chris-belcher/electrum-personal-server#links-to-other-setup-guides).

To solve the "bad master public key format" it looks like inside the config file theres an uncommented line that starts with `Welc`, remove that.

**Comment by NullSense** [comment]
> Firstly, your censoring of your bitcoin addresses isn't good enough and it's still possible to figure out what those 3 addresses are. You need to blank out the whole address (ideally you'd create a brand new wallet now)

Unrelated, but my curiosity got the best of me, how is that done, or how would that be done?

**Comment by chris-belcher** [comment]
> Unrelated, but my curiosity got the best of me, how is that done, or how would that be done?

OP has left the first 20 or so characters of the address uncensored. If they were ever used in a transaction then the entire blockchain could be searched for those prefixes which would result in finding the full address. Another way works by using the checksum which is in each address, and use a bit of CPU power to bruteforce the remaining few characters (the length of each address is known too)
