### ISSUE TITLE
Electrum EPS Server displays error message when connecting

### ISSUE THREAD

**Issue by jonjonez** [chris-belcher/electrum-personal-server#207]
![image](https://user-images.githubusercontent.com/23480437/88878387-40f64080-d1fe-11ea-88f8-89a8a1a6982c.png)

tx index enabled, no pruning

I ran the same command as always (electrum-personal-server path/myuser/...), I've checked the config.ini to find an error and nothing, everything is normal.

I haven't done anything that justified this mistake.

I am no longer able to use EPS to connect to Electrum.

**Comment by chris-belcher** [comment]
Maybe you're already running EPS on another terminal?

Try running `netstat -l` to see if the port 50002 really is open. There are other commands which can tell you which process is using that port (search the web for them)

If you can't get that to work, you can edit the port in the config file (e.g. to 50003 instead) and then tell electrum to connect to the same port.
