### ISSUE TITLE
EPS logging at debug level despite config.cfg setting of INFO

### ISSUE THREAD

**Issue by pox** [chris-belcher/electrum-personal-server#208]
This is 99% probably my fault, so pardon the ticket (is there a better place to ask for support help?).

I have the following in my `config.cfg`:

```
[logging]
log_level_stdout = INFO
```

And EPS is running with the above config file as the first command line parameters (also, I know it's the active config file because the xpubs I've been adding are being indexed).

Despite this the log file at `/tmp/` has many `DEBUG` level lines. And it's growing and growing on my poor raspi.

It should be noted that the log lines that reach `journald` are INFO only. So the log level seems to be applied to stdout but not to file log targets perhaps?

**Comment by pox** [comment]
I'm noticing the file log handler seems to be hardcoded to log in DEBUG level:

https://github.com/chris-belcher/electrum-personal-server/blob/cea0acc753a1d4da71b7322fc74844121d26e22f/electrumpersonalserver/server/common.py#L353

Is this by design?

**Comment by chris-belcher** [comment]
Yes the config file option only controls stdout.

The latest version of EPS has much less stuff being written to the log file, so update if you're not using it already.

Bitcoin Core's log file also perpetually grows, why doesn't that cause problems for your pi? (or does it?)

**Comment by pox** [comment]
Will update. 

Core's log seems to be rotating, or in any case it's not anywhere as big as the debug log EPS is generating for me. It's about 10MB after running for a month. EPS gets to 10MB in about an hour.

Why not use the same log level setting for the file handler as well? Is this by design?

**Comment by pox** [comment]
Well I patched it to use the config's log level for the file handler as well, lmk if you'd like a PR.

Also, DAMN, this new version is so much faster to boot up. I think it's at least 8x faster for me. Much appreciated!

**Comment by pox** [comment]
:v: https://blockstream.info/tx/fffeef228271ffb929e0f14e73256fa30ca61050cdfe3f2cb8015361780e6f3d

**Comment by chris-belcher** [comment]
The point of writing to the debug log is to that bugs can be more easily studied. So ideally the messages would be there even if the user doesnt want to see them in stdout.

The old version did write far too much to the debug output, with messages that didn't add much value. The new version writes much less. The commits which did that are https://github.com/chris-belcher/electrum-personal-server/commit/6fa79cec1023395810599f8d8fced18b30bb8610 and https://github.com/chris-belcher/electrum-personal-server/commit/659b4c00278a69c9f817f33fad2fdb7d3f34f994

And yes the new version is much faster to start up, it indirectly uses the libsecp256k1 library which does fast elliptic curve calculations. The previous version did the calculations in slow pure python.
