### ISSUE TITLE
Instructions to create a wallet without private keys (once bitcoind supports it)

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#21]
There's a PR by @jonasschnelli which allows Bitcoin Core to generate wallets with private key support explicitly disabled: https://github.com/bitcoin/bitcoin/pull/9662

Once that's merged, the README here should point that out. 

Even better, if possible, would be for the server script to check this flag is set and refuse to run otherwise (at least for new wallets).

**Comment by chris-belcher** [comment]
Yes, good idea.
