### ISSUE TITLE
Requested wallet does not exist or is not loaded

### ISSUE THREAD

**Issue by bar17** [chris-belcher/electrum-personal-server#210]
I was running Core 0.19.1 and EPS 0.2.0. I shut off my server for a month or so when I moved and on reboot / restart of EPS I got this error:

```
$ ~/electrum-personal-server-eps-v0.2.0$ electrum-personal-server ~/electrum-personal-server-eps-v0.2.0/config.ini

INFO:2020-08-15 23:34:10,778: Starting Electrum Personal Server
INFO:2020-08-15 23:34:10,779: Logging to /tmp/electrumpersonalserver.log
ERROR:2020-08-15 23:34:10,785: JsonRpcError({'code': -18, 'message': 'Requested wallet does not exist or is not loaded'})
ERROR:2020-08-15 23:34:10,785: Wallet related RPC call failed, possibly the bitcoin node was compiled with the disable wallet flag
```

```
$ bitcoin-cli listwallets

[
  ""
]
```

Adding the wallet manually in `~/.bitcoin/bitcoin.conf` file with `"wallet=~/.bitcoin/electrumpersonalserver/wallet.dat"` forces the wallet to appear with "bitcoin-cli listwallets" but gives the same EPS error.

I created a new wallet `bitcoin-cli createwallet electrumpersonalserver-2 true` and added the wallet in the EPS config.ini file. 

Same error. 

I updated Core to 0.2.0 and EPS to 0.2.1.1 and the error is the exact same.

The weird thing is this was working fine 1-2 months ago. Any help would be appreciated. Thank you.

**Comment by chris-belcher** [comment]
Hmm, not sure. Maybe check that in your `config.ini` file it says `wallet_filename = electrumpersonalserver-2` ?

**Comment by bar17** [comment]
I did update this with the new file. I will try and delete all traces of a wallet in core and start over and re-update this thread.

**Comment by bar17** [comment]
It's working. I used the wallet option in both core and EPS.

```
bitcoin.conf
wallet = electrumpersonalserver
```

```
config.ini
wallet = electrumpersonalserver
```
I did not use any absolute file names, as I had done previously.
When I restarted bitcoin core it was "rescanning..." for 10-15 minutes. Running config.ini with EPS worked just fine.
