### ISSUE TITLE
EPS and  Bitcoin Core version v0.19.1-satellite0.1.2

### ISSUE THREAD

**Issue by 0691tuta** [chris-belcher/electrum-personal-server#211]
Hi, 
Is the latest EPS tested with the blockstream modified version of Core v0.19.1 ? 
I get the following message when I try to start the server: 
INFO:2020-09-03 12:12:19,062: Starting Electrum Personal Server 0.2.1.1
INFO:2020-09-03 12:12:19,062: Logging to /tmp/electrumpersonalserver.log
ERROR:2020-09-03 12:12:19,067: JsonRpcError({'code': -18, 'message': 'Requested wallet does not exist or is not loaded'},)
ERROR:2020-09-03 12:12:19,067: Wallet related RPC call failed, possibly the bitcoin node was compiled with the disable wallet flag

Right now I have the latest version node software for the satellite setup and EPS-0.2.1.1  
Thanks. 
*************************************************************************
Options used to compile:
  with wallet   = yes
  with gui / qt = yes
    with bip70  = no
    with qr     = yes
  with zmq      = yes
  with test     = yes
    with prop   = no
    with fuzz   = no
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  sanitizers    = 
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = linux
  build os      = 

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      =   -fstack-reuse=none -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wformat -Wvla -Wswitch -Wformat-security -Wredundant-decls  -Wno-unused-parameter -Wno-implicit-fallthrough   -g -O2 -march=native
  LDFLAGS       = -pthread  -Wl,-z,relro -Wl,-z,now -pie  
  ARFLAGS       = cr

**Comment by chris-belcher** [comment]
The relevant error is `Requested wallet does not exist or is not loaded`

So check that the wallet file configured in the `config.ini` file is the same as the one configured in `bitcoin.conf`.

That error message about compiling without the wallet flag is wrong in this case, I'll change the message to something more helpful.

**Comment by 0691tuta** [comment]
I left the config.ini  "wallet_filename ="  field blank and tried to startup, got a different message:

INFO:2020-09-03 20:03:01,189: Starting Electrum Personal Server 0.2.1.1
INFO:2020-09-03 20:03:01,189: Logging to /tmp/electrumpersonalserver.log
ERROR:2020-09-03 20:03:01,196: ValueError("JsonRpcError({'code': -5, 'message': 'A function is needed within P2SH'},)",)
ERROR:2020-09-03 20:03:01,196: Descriptor related RPC call failed. Bitcoin Core 0.20.0 or higher required. Exiting..

Thanks.

**Comment by chris-belcher** [comment]
You need Core version 0.20. Does blockstream's fork have a version of 0.20 ?

A possible alternative is to downgrade to the older version of EPS: https://github.com/chris-belcher/electrum-personal-server/releases/tag/eps-v0.2.0 But you miss out on some features doing this.

**Comment by 0691tuta** [comment]
Unfortunately the blockstreams fork is still v0.19 https://github.com/Blockstream/bitcoinsatellite/releases
Cheers for the link.
