### ISSUE TITLE
Floating point issue in get_address_balance()

### ISSUE THREAD

**Issue by jmacxx** [chris-belcher/electrum-personal-server#219]
**[N.B.] this is a very minor issue which does not affect anything in the Electrum UI, AFAIK.**

In some cases, `get_address_balance()` and ` generate_new_history_element()` returns a result which is slightly different than expected (a difference of 1 satoshi).  This is due to the internal representation of a floating point number in the `Decimal` class.

    >>> from decimal import *
    >>> x = Decimal(0.25054)
    >>> print(x)
    0.25053999999999998493649400188587605953216552734375

Due to the following line (transactionmonitor.py#L76)

    value = int(Decimal(utxo[0]) * Decimal(1e8))

  Proposed fix is to [convert to string](https://stackoverflow.com/questions/286061/decimal-place-issues-with-floats-and-decimal-decimal#286064) before passing it into Decimal.  

    value = int(Decimal(str(utxo[0])) * Decimal(1e8))

----

![image](https://user-images.githubusercontent.com/47253594/94493370-097e2300-01b2-11eb-99a3-6afbe9f41443.png)

**Comment by chris-belcher** [comment]
Nice find. Thanks for the issue.
