### ISSUE TITLE
getaddressesbyaccount is deprecated

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#22]
It's scheduled to be removed in Bitcoin Core v0.18. This is used in `get_scriptpubkeys_to_monitor`.

It results in an error on `bitcoind` master, unless you launch with `-deprecatedrpc=accounts`.

I haven't checked exactly how the server uses this feature. Simply replacing it with `getaddressesbylabel` results in another error: `No addresses with label electrum-watchonly-addresses`. That new error is a feature apparently: https://github.com/bitcoin/bitcoin/pull/12892#issuecomment-379016369 (use Incognito window if you get a Unicorn)

> * `getaddressesbylabel` throws an error if called for a label that doesn't exist

You may need to call `listlabels` first to see if it exists.

**Comment by chris-belcher** [comment]
Thanks for telling me.

EPS needs the functionality of listing every imported address. According to https://bitcoin.stackexchange.com/questions/70311/getaddressesbyaccount-rpc-alternative there will be new RPC calls added to provide this functionality. When that happens that call to getaddressesbyaccount can be trivially changed to getaddressesbylabel

**Comment by Sjors** [comment]
You could use `getnetworkinfo` and then check if `version >= 160100`, which should work unless for some reason the `16.1` or `17.0` release doesn't include the current master.
