### ISSUE TITLE
need to load wallet on startup - bug?

### ISSUE THREAD

**Issue by monkey-jsun** [chris-belcher/electrum-personal-server#222]
I followed your instruction and created a dedicated wallet for EPS, electrumpersonalserver.  I found I had to add the following code in order to start seamlessly.  Otherwise I would need to manually open the EPS wallet before starting EPS.  Is this a bug?

```python
--- server/common.py.orig	2020-10-19 17:41:51.604894210 +0000
+++ server/common.py	2020-10-19 18:01:02.419901970 +0000
@@ -391,6 +391,14 @@
         wallet_filename=config.get("bitcoin-rpc", "wallet_filename").strip(),
         logger=logger)
 
+    # load/open the wallet file, in case it is not opened yet
+    wallet_filename=config.get("bitcoin-rpc", "wallet_filename").strip()
+    try:
+        if wallet_filename:
+            rpc.call("loadwallet", [wallet_filename])
+    except Exception:
+        pass
+
     #TODO somewhere here loop until rpc works and fully sync'd, to allow
     # people to run this script without waiting for their node to fully
     # catch up sync'd when getblockchaininfo blocks == headers, or use
```

**Comment by chris-belcher** [comment]
Thank you. Yes you're right. Though I think a better solution would be to tell people to add their new wallet to their `bitcoin.conf` file as `wallet=yourwalletname`. The README tells people to do `bitcoin-cli createwallet electrumpersonalserver true` which doesnt automatically load the wallet at startup.

**Comment by monkey-jsun** [comment]
Agree that adding to bitcoin.conf is a better solution.  I was actually looking for that solution, but google did not find it actually.

**Comment by chris-belcher** [comment]
I'll reopen the issue until the README is edited (by me when I get time, or by someone else with a pull request)
