### ISSUE TITLE
EPS no longer works with Electrum 4.0.6

### ISSUE THREAD

**Issue by Steffen-8** [chris-belcher/electrum-personal-server#226]
Following an upgrade from Electrum 4.0.4 to 4.0.6 (Lightning enabled by default) the EPS connection no longer works. There is no way to disable the Lightning functionality of Electrum!?

After a client connect immediately follows a disconnet. The wallets are no longer usable!!!

For a usee who does not need Lightning there should be a way to continue to use the EPS.

Please adapt EPS or it will become completely useless!

**Comment by chris-belcher** [comment]
I don't have time to fix this for a while I'm afraid, I suggest downgrading Electrum if you can.

Did you create any LN channels? It's odd that LN functionality would cause the Electrum/EPS connection to break if you're not actually using LN. Hopefully it's something else which can then be fixed more easily than implementing LN in Electrum.

**Comment by Steffen-8** [comment]
I have not created any LN channels but I looked into the menus and maybe activated something this way? At least the Electrum client started to collect LN node lists and successfully finished that.

I did a downgrade to 4.0.4 and it works. Interestingly even now the Electrum client shows an active LN symbol and informs about an updated LN node list. Nevertheless it shows no disconnect behaviour as the 4.0.6 version does ...?

Would be nice if you could check for the reason of the disconnect but I understand that everybody has to prioritize his TODOs ;-).

**Comment by hMsats** [comment]
I'm running Electrum 4.0.5 and indeed no connection with EPS anymore while I can still connect to my public electrum server. I haven't opened any lightning channels.

**Comment by chris-belcher** [comment]
I just tried Electrum 4.0.9 with EPS and it worked for me. Nobody else has mentioned this problem so it looks like electrum fixed whatever was causing this before I could get round to it.

**Comment by hMsats** [comment]
It still wasn't working for me, so I investigated a little. 

What solved it was looking in `/tmp/electrumpersonalserver.log` where I found this:

`DEBUG:2021-02-24 07:47:14,185: 192.168.178.1 not in whitelist, closing`

In `config.ini` I always only had:

`ip_whitelist = MyIPAddress` which had always worked. Adding that local IP address solved my problem so:

`ip_whitelist = 217.104.75.11 192.168.178.1`

and Electrum connected like a charm. I have no idea why I suddenly had to add this local IP address but to be honest I'm not a genius when it comes to IP addresses :-)

I start Electrum like this (which had always worked):

`python3 /home/user/Electrum-4.0.9/run_electrum --oneserver --server electrum.bitkoins.nl:51112:s`

I'm probably doing something illogical but glad it works again!

**Comment by chris-belcher** [comment]
I don't know either why that IP had to be added to the whitelist.

**Comment by hMsats** [comment]
Well, let's see what @Steffen-8 has to say about this. BTW I run Electrum on a laptop and connect to my server (Bitcoin node), so it's not running on the same machine.

**Comment by Steffen-8** [comment]
I just updated my setup to 4.0.9 and indeed the error disappeared. 

For me whitelisting was not the issue, I didn't use it. I have no idea what the real problem was?

Nevertheless thanks @chris-belcher for looking this issue! At least it encouraged me to try 4.0.9 and return to the standard update cycle!
