### ISSUE TITLE
eps don't connect anymore

### ISSUE THREAD

**Issue by svpi11** [chris-belcher/electrum-personal-server#229]
Good morning !

Since today I have a new problem to connect eps to my full bitcoin node.
I've been doing it always the same way since this summer, and it worked, but now after some month without doing it (and maybe a new update to Kubuntu 20.10 last october ?) it doesn't start anymore.

Here is what I have, doing the usual command line "electrum-personal-server config.ini" in the folder of eps, with the usual config.ini file I used before: 

INFO:2020-12-21 11:15:32,697: Starting Electrum Personal Server 0.2.1.1
INFO:2020-12-21 11:15:32,759: Logging to /tmp/electrumpersonalserver.log
WARNING:2020-12-21 11:15:32,896: Unable to find .cookie file, try setting `datadir` config

Could someone help me ? I didn't find more logs, but maybe someone can help me to find the log file to explain more ?

Thank you very much,

**Comment by shesek** [comment]
It seems like either your `datadir` is misconfigured, or Bitcoin Core is not running.

**Comment by svpi11** [comment]
Thank you for your answer ! 😀 
Sadly Bitcoin Core was running behind, as I did before several times when I was working...
I didn't modified any config file too... But probably an update did it somehow did it ?

Sorry but what is exactly my datadir ?

**Comment by dhammel** [comment]
@svpi11 @svpi11 Your datadir is the Bitcojn directory specified when first starting Bitcoin Core, where your blockchain and wallet stored. Default is ~/.bitcoin. You have to specify location to it in the config.ini. Make sure that bitcoin RPC server is running.

**Comment by svpi11** [comment]
Thank you very much to all for your answers !!
I've found the solution by myself and I'm confused... Another program just simply wrote into my bitcoin.conf file without I realized it... So I removed the line of this program.

Thank you again, and sorry for disturbing ;) 
Thanks for your work by the way !
