### ISSUE TITLE
Configure address type

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#23]
Electrum seems to use `xpub...`, `ypub...` an `zpub...` to distinguish between legacy, p2sh-segwit and bech32 derivations, but afaik that's not a standard.

This causes problems if you e.g. export the xpub from a ledger, and simply replacing "x" with "y" or "z" isn't a viable workaround either because the checksum won't match.

Adding an explicit address type config option would be useful here.

As a workaround, either get the `ypub` / `zpub` from Electrum, or edit `deterministicwallet.py` and change `SingleSigP2PKHWallet`  in `parse_electrum_master_public_key` (3...) to `SingleSigP2WPKH_P2SHWallet` or `SingleSigP2WPKHWallet` (bech32).

**Comment by chris-belcher** [comment]
Edited README here https://github.com/chris-belcher/electrum-personal-server/commit/9905d94ac900f47f9a7ed847d4520472b5838391
