### ISSUE TITLE
Failed to execute common script

### ISSUE THREAD

**Issue by spbubble123** [chris-belcher/electrum-personal-server#231]
I'm trying to get EPS working, but I'm stuck.
Running the electrum-personal-server.exe or the rescan.bat on Windows 7 in a command.exe window gives me "Failed to execute script common"
I've got a full bitcoin-qt node running, all 340Gb, and I followed the setup guide. 
I've created a new bitcoin core wallet for the exercise.
When I run the rescan.bat config.ini I get [2684] Failed to execute script common
and when I run electrum-personal-server.exe config.ini I get [1436] Failed to execute script common
Any ideas please?

Here is a fuller listing
F:\Portafoglio\EPS\epsw>electrum-personal-server.exe config.ini
Traceback (most recent call last):
  File "electrumpersonalserver\server\common.py", line 517, in <module>
  File "electrumpersonalserver\server\common.py", line 363, in main
  File "configparser.py", line 696, in read
  File "configparser.py", line 1110, in _read
configparser.ParsingError: Source contains parsing errors: 'config.ini'
        [line 11]: 'xpub661xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n'
[4556] Failed to execute script common

**Comment by chris-belcher** [comment]
The important error message seems to be: `configparser.ParsingError: Source contains parsing errors: 'config.ini'`

Copypaste your config file here with sensitive data (e.g. the master public keys) removed. It's likely to you have a typo somewhere or something.

**Comment by spbubble123** [comment]
# Electrum Personal Server configuration file

# Lines starting with # are called comments which are ignored.
# For a line to have effect it must not start with #

# The most important options are towards the top of the file

[master-public-keys]
# Add electrum wallet master public keys to this section
# In electrum then go Wallet -> Information to get the mpk
xpub661MyMwAqRbcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMPZ

#any_name_works = xpub661xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMgEF

# Multiple master public keys maybe added by simply adding another line
#my_second_wallet = xpubanotherkey

# Multisig wallets use format `required-signatures [list of master pub keys]`
# this example is a 2-of-3 multisig wallet
#multisig_wallet = 2 xpub661MyMwxxxxxxxxxxxxxxxxxxxxxxxxxMgEF 


[bitcoin-rpc]
host = 127.0.0.1
port = 8332
#add the bitcoin datadir to search for the .cookie file created by the
# node, which avoids the need to configure rpc_user/pass
#leave this option empty to have it look in the default location
datadir = F:\Portafoglio\Purse\catena
#if you dont want to use the .cookie method with datadir, uncomment to config u/p here
#rpc_user =
#rpc_password =

#to be used with the multi-wallet feature
# see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md#multi-wallet-support
# empty means default file, for when using a single wallet file
wallet_filename = electrumpersonalserver

# how often in seconds to poll for new transactions when electrum not connected
poll_interval_listening = 30
# how often in seconds to poll for new transactions when electrum is connected
poll_interval_connected = 1

# Parameters for dealing with deterministic wallets
# how many addresses to import first time, should be big because if you import too little you may have to rescan again
initial_import_count = 1000
# number of unused addresses kept at the head of the wallet
gap_limit = 25

[electrum-server]
# 0.0.0.0 to accept connections from any IP
#127.0.0.1 to accept from only localhost
host = 127.0.0.1
port = 50002

# space-separated whitelist of IP addresses
# accepts CIDR notation eg 192.168.0.0/16 or 2a01:4f8:1f1::/120
# star (*) means all are accepted
# generally requires host binding (above) to be 0.0.0.0
ip_whitelist = *

#SSL certificate
#uses the default one, which is fine because by default nobody should be
# allowed to connect to your server or scan your packets
#to generate another certificate see https://github.com/spesmilo/electrum-server/blob/ce1b11d7f5f7a70a3b6cc7ec1d3e552436e54ffe/HOWTO.md#step-8-create-a-self-signed-ssl-cert
certfile = certs/cert.crt
keyfile = certs/cert.key

# Option for disabling the fee histogram calculation
# It improves server responsiveness but stops mempool-based Electrum features
# This is useful on low powered devices at times when the node mempool is large
disable_mempool_fee_histogram = false

# Parameter for broadcasting unconfirmed transactions
# Options are:
# * tor-or-own-node  (use tor if tor is running locally, otherwise own-node)
# * own-node         (broadcast using the connected full node)
# * tor              (broadcast to random nodes over tor)
# * system <cmd> %s  (save transaction to file, and invoke system command
#                     with file path as parameter %s)
broadcast_method = tor-or-own-node

# For tor broadcasting (broadcast_method = tor) configure
# the tor proxy host and port below
tor_host = localhost
tor_port = 9050

# = Notes on tor broadcasting =
# If using tor broadcasting, make sure you set `walletbroadcast=0` in
#  your bitcoin.conf file
# If your full node is connected to the internet only via tor then you dont
#  need separate tor broadcasting


[watch-only-addresses]
#Add individual addresses to this section, for example paper wallets
#Dont use this section for adding entire wallets, instead use the
# above section `master-public-keys`

#addr = 1DuqpoeTB9zLvVCXQG53VbMxvMkijk494n

# A space separated list is also accepted
#my_test_addresses = 3Hh7QujVLqz11tiQsnUE5CSL16WEHBmiyR 1PXRLo1FQoZyF1Jhnz4qbG5x8Bo3pFpybz bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq

# multiple addresses may also be added in separate lines (like master public keys above)
#addr2 = 3anotheraddress


[logging]
# Section for configuring the logging output

# The log level. Logging messages less severe than this will not be displayed
#options are 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
#Information printed to the log file is always at level DEBUG
log_level_stdout = INFO

# Location of log file, leave empty to use the default location in temp dir
log_file_location =

# Whether to append to log file or delete and overwrite on startup
append_log = false

# Format to use for logging messages
#see docs https://docs.python.org/3/library/logging.html#formatter-objects
log_format = %(levelname)s:%(asctime)s: %(message)s

**Comment by spbubble123** [comment]
[redactedconfig.ini.txt](https://github.com/chris-belcher/electrum-personal-server/files/5808453/redactedconfig.ini.txt)

**Comment by chris-belcher** [comment]
You've just added the master public key on a line on its own, but the file takes `key = value` pairs.

e.g. you wrote:
```
xpub661MyMwAqRbcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMPZ
```

But you should write

```
my_mpk = xpub661MyMwAqRbcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMPZ
```

**Comment by spbubble123** [comment]
Thanks very much. That now works OK.
