### ISSUE TITLE
Set ~/.electrum/config to Local Server

### ISSUE THREAD

**Issue by McMurdo2009** [chris-belcher/electrum-personal-server#233]
I'm always careful to launch Electrum with `electrum --oneserver --server localhost:50002:s` as is recommended to not connect to any other server and share my xpub. However, I'd appreciate instructions for changing my ~/.electrum/config file to automatically use these options, lest I one day accidentally type "electrum" into my terminal and launch it with default settings.

**Comment by jmacxx** [comment]
You can use the `setconfig` option of electrum to do it for you:

    electrum setconfig oneserver true
    electrum setconfig server localhost:50002:s


The config file will then contain:

    "oneserver": true,
    "server": "localhost:50002:s",
