### ISSUE TITLE
Trezor Wallet History Missing (EPS + Electrum)

### ISSUE THREAD

**Issue by ygyzys83** [chris-belcher/electrum-personal-server#239]
Chris-

I'm running Bitcoin Core on a RasPi 3. I installed EPS and Electrum Wallet. I added my Trezor master public keys (generated from Electrum wallet -> information after adding each of the Trezor wallets to Electrum Wallet software) to the EPS config file (added to the "Master Public Keys" section, not the "Watch-Only Addresses" section - is this wrong?) and ran an initial EPS scan of the blockchain starting at block height 1. 

My issue is that after EPS finished compiling the history and the EPS server was re-launched, none of my Trezor wallets were showing any history in the Electrum Wallet software. I confirmed that the Trezor was properly connected, and that Electrum Wallet was synchronized and properly connected to just my node. There were no issues with the initial EPS blockchain scan that I could tell, so I'm confused and not sure what I'm missing. Any guidance is much appreciated. Thank you.

**Comment by chris-belcher** [comment]
Adding to "master public keys" is correct.

When starting up EPS it should print out the first three addresses of the wallet, you should check that they are correct.

**Comment by ygyzys83** [comment]
Thanks for the response. I realized it was because I chose the wrong address type when I loaded my trezor wallets into electrum wallet. When I chose the right address type (ypub) and re-scanned with EPS, the history was there.

On a separate note: is there a way to use EPS + Electrum on a separate laptop from the Bitcoin node? My understanding is that this can be done with Tor, however it also seems possible by changing the information in the [bitcoin-rpc] section of the EPS config, and making corresponding updates to the bitcoin.conf file...

**Comment by chris-belcher** [comment]
Yes, you need to tell bitcoin core to make the RPC port accessible from other computers (use `netstat -l` to check), then tell EPS to connect to that port.

However I don't know why someone would do this, it's usually better off having EPS and Core on the same machine. And then connecting your Electrum to EPS over the internet (perhaps via a SSH tunnel)
