### ISSUE TITLE
'NoneType' object is not subscriptable in transactionmonitor.py

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#24]
I'm seeing `[DEBUG] utxo not found(!)` and then the server crashes with:

```
  File "electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 219, in generate_new_history_element
    total_input_value += int(Decimal(utxo["value"]) * Decimal(1e8))
TypeError: 'NoneType' object is not subscriptable
```

I think this happened as a result of me spending an unconfirmed (very low fee) transaction using another transaction (with a low fee).

I added both raw transactions to the node and they do show up with `getrawtransaction`, but the error won't go away.

The server log shows `adding obtained tx` for the parent transaction. Crash seems to happen while processing the child. I think it's trying to access a (confirmed) parent of the parent, using `gettxout`. Without txindex it won't find that.

**Comment by chris-belcher** [comment]
Done something here https://github.com/chris-belcher/electrum-personal-server/commit/8338b0883b78bdbb36af1d9d2d01faf11c9312aa

**Comment by Sjors** [comment]
`server.py` no longer crashing for me. Fees for incoming transactions are shown as unknown, not as a negative value.
