### ISSUE TITLE
Where is the banner located?

### ISSUE THREAD

**Issue by AngeloMetal** [chris-belcher/electrum-personal-server#242]
Sorry if the answer is obvious, but I've been scratching my head half an hour now. I've googled it but haven't found anything. Where is the banner located?

**Comment by chris-belcher** [comment]
On electrum go View -> Show Console

**Comment by AngeloMetal** [comment]
I mean, how can I change it. On electrumx, there is a banner file located in the source.

**Comment by chris-belcher** [comment]
EPS doesn't have a feature to change the banner. You would have to edit the source code to change it.

**Comment by AngeloMetal** [comment]
Oh, okay. I'm closing this.
