### ISSUE TITLE
Can I make a public server with EPS?

### ISSUE THREAD

**Issue by AngeloMetal** [chris-belcher/electrum-personal-server#243]
I know that it sounds dumb, since it's a personal server, but is it possible to make it available for others, just like it's done in electrumx? I find EPS pretty comfortable implementation and I was wondering if it'd be possible.

I tried connecting to my electrum personal server with LAN, but it didn't seem to work. Is it exclusively for the machine that is being installed, locally? I'm asking because in [line 50](https://github.com/chris-belcher/electrum-personal-server/blob/d31fa2d0ab47cb0d3d0d0f071e00fe90d247e603/config.ini_sample#L50), it says that it can accept connections from any IP.

Thanks.

**Comment by chris-belcher** [comment]
Did you definitely set `host = 0.0.0.` in that section of the config file you linked ?

**Comment by AngeloMetal** [comment]
Yes, I set it to ``0.0.0.0``

**Comment by chris-belcher** [comment]
Did you correctly input the server IP address into the client?

You could also try running `netstat -l` on the command line (on linux) to check if EPS has opened a port binded to 0.0.0.0

**Comment by AngeloMetal** [comment]
I will, but what matters to me right now if it's possible to expose it over WAN.

**Comment by chris-belcher** [comment]
Have you read this? https://github.com/chris-belcher/electrum-personal-server#exposure-to-the-internet

Exposure to WAN could allow anyone else out the on the internet to figure out which bitcoin addresses are yours.

**Comment by AngeloMetal** [comment]
Oh wait, I had totally forgot about that. I can't run EPS without having inserted some addresses/master keys first, can I? I think that on electrumx it's possible to return you the balance of any address since it keeps the txindex.

**Comment by chris-belcher** [comment]
Yes that's right. ElectrumX creates a huge database contained every bitcoin address that was ever used. That's why it can synchronize any Electrum wallet without needing to configure beforehand. EPS needs to be configured beforehand but requires much much less disk space, and it much quicker to set up.

**Comment by AngeloMetal** [comment]
I guess that I can't configure that same setting, electrumx has, to EPS. I just face a lot of issues on my way to install electrumx and your server implementation was much more simpler than it.
