### ISSUE TITLE
BitBox 02 EPS

### ISSUE THREAD

**Issue by andyR14** [chris-belcher/electrum-personal-server#244]
When I connect to the EPS via the BitBox02 app, 27 addresses are scanned then it hangs and the message repeatedly appears in the EPS log: WARNING :: Address not known to Electrum Personal server, hash (address)

The master public key is stored correctly, the first three receiving addresses are correct and the correct transaction is displayed in the Bitcoin core wallet (electrum watch only).

Before that I did a rescan.

**Comment by chris-belcher** [comment]
That error message means the client is requesting addresses that the server doesn't know about. Maybe Bitbox is doing something I don't know about, try contacting them?

**Comment by andyR14** [comment]
I´ve contacted shiftcrypto.ch and will keep you informed.

**Comment by andyR14** [comment]
Here is the solution: the BitBoxApp works with a zPub as default and yPub as fallback. I had to enter both addresses in the config.ini. Now it works fine.
