### ISSUE TITLE
confused with different wallets in settings

### ISSUE THREAD

**Issue by telejoshi** [chris-belcher/electrum-personal-server#245]
Hello there,

I'm running a Bitcoin Node on a raspberry pi (it's working). I can't wrap my head around configuring EPS though.

Setup:
- Bitcoin Core 0.21.1 / electrumpersonalserver 0.2.2 on Raspberry Pi 4
- Electrum Wallet on my PC (Windows)

What I've done so far:
- installed electrumpersonalserver
- created a wallet named electrum (with bitcoin-cli -datadir=/mnt/biti createwallet electrum true)

config.ini:
> [master-public-keys]
> mywallet = zpub(...)                 /public master key of my original (read-only) wallet I use on Windows
> [bitcoin-rpc]
> host = 127.0.0.1
> port = 8332
> datadir = /mnt/biti
> wallet_filename = electrum      /wallet I've created on Bitcoin Core for EPS

I've added the public key of my Electrum wallet I run on Windows to config.ini. I think I just don't understand why there must be a wallet on my Bitcoin Node, too. There's a wallet called "electrum" on my node but also a different wallet on my Computer. Would it be better to open that same wallet (read only) on my Bitcoin Node?

**Comment by chris-belcher** [comment]
The way Electrum Personal Server works is that it generates the bitcoin addresses of your Electrum wallet and then imports them as watch-only into the Bitcoin node. EPS will then (possibly after a rescan) obtain transactions from the Bitcoin node and use that to notify the Electrum client of new and old transactions. For this to work the Bitcoin node must also have a wallet file specially for EPS. This Bitcoin node wallet file only contains watch-only addresses.

**Comment by telejoshi** [comment]
> For this to work the Bitcoin node must also have a wallet file specially for EPS. This Bitcoin node wallet file only contains watch-only addresses.

So in other words that extra Wallet is needed for EPS to work? Thanks for the explanation.
