### ISSUE TITLE
EPS Doesn't Work with Imported Private Keys using Electrum - "Address not known to server"

### ISSUE THREAD

**Issue by Arns** [chris-belcher/electrum-personal-server#265]
When importing via File -> Restore -> Import Bitcoin Addresses or Private Keys using format p2wpkh:Kz... I get the following warning in the EPS console:

WARNING:2022-04-03 15:27:04,943: Address not known to server, hash(address) = 08fa2....
Check that you've imported the master public key(s) correctly. The first three addresses of each key are printed out on startup,
so check that they really are addresses you expect. In Electrum go to Wallet -> Information to get the right master public key.

I'm running Bitcoin Core + EPS + Electrum. I'm sure I'm missing something, because if I point Electrum to a 3rd party EPS server, everything syncs up just fine...

**Comment by chris-belcher** [comment]
You need to add the bitcoin addresses corresponding to your private keys to the config file in the `watch-only-addresses` section: https://github.com/chris-belcher/electrum-personal-server/blob/master/config.ini_sample#L98-L109

**Comment by Arns** [comment]
@chris-belcher you're right, that resolved it. I originally had difficulty figuring out how to get the xPub but i found that electrum did indeed show it. Little clunky of a process but it works! Thanks.
