### ISSUE TITLE
Startup error with bitcoin core 23.0

### ISSUE THREAD

**Issue by waage** [chris-belcher/electrum-personal-server#266]
```
INFO:2022-04-25 17:11:27,328: Synchronizing mempool . . .
Traceback (most recent call last):
  File "/home/norbert/.local/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
  File "/home/norbert/.local/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 494, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/norbert/.local/lib/python3.8/site-packages/electrumpersonalserver/server/common.py", line 121, in run_electrum_server
    mempool_sync.initial_sync(logger)
  File "/home/norbert/.local/lib/python3.8/site-packages/electrumpersonalserver/server/mempoolhistogram.py", line 57, in initial_sync
    self.poll_update(-1)
  File "/home/norbert/.local/lib/python3.8/site-packages/electrumpersonalserver/server/mempoolhistogram.py", line 111, in poll_update
    fee_rate = 1e8*mempool_tx["fee"] // mempool_tx["vsize"]
KeyError: 'fee'
```

**Comment by mhooSec** [comment]
I get exactly the same error after upgrading Bitcoin Core to 23.0

**Comment by hMsats** [comment]
Same error

**Comment by hMsats** [comment]
I found a work around **for now**:

In `/home/user/.local/lib/python3.8/site-packages/electrumpersonalserver/server/mempoolhistogram.py` 

I changed line 108: 

`mempool_tx = self.rpc.call("getmempoolentry", [txid])`

into

`mempool_tx = self.rpc.call("getmempoolentry -deprecatedrpc=fees", [txid])`

and EPS was working again. This was changed in version 23 of Bitcoin Core

```
- - The top-level fee fields `fee`, `modifiedfee`, `ancestorfees` and `descendantfees`
  returned by RPCs `getmempoolentry`,`getrawmempool(verbose=true)`,
  `getmempoolancestors(verbose=true)` and `getmempooldescendants(verbose=true)`
  are deprecated and will be removed in the next major version (use
  `-deprecated=fees` if needed in this version).
```

**Comment by Liongrass** [comment]
Ah awesome, that config worked for me too

**Comment by hMsats** [comment]
I get the impression that my proposed solution above (changing line 108 in mempoolhistogram.py) increases the cpu usage of EPS considerably. It’s now often at the top of the Unix top command and also my measure of general cpu usage of my server has gone up a lot.

**Comment by andrewtoth** [comment]
@hMsats indeed it would. A better approach would be https://github.com/chris-belcher/electrum-personal-server/pull/273/commits/008d9acd5f968665c471931facac84188fd5a9b4, which you can try until that patch gets merged.

**Comment by hMsats** [comment]
@andrewtoth Thanks a lot. EPS is working fine now, without the high cpu usage! I switched to adding `deprecatedrpc=fees` to `bitcoin.conf` but have removed that now. Electrum connected only to my EPS server is also working.
