### ISSUE TITLE
"electrum-personal-server-rescan" file does not appear in the bin python folder on Mac

### ISSUE THREAD

**Issue by dimix000** [chris-belcher/electrum-personal-server#267]
After following the tutorial for Mac, the only issue appears to be that the "electrum-personal-server-rescan" file is not created in the Python library, only the "electrum personal server" file appears, making it impossible to rescan the blockchain when adding old xpubs in the config.ini file.

Is there a solution to that?

**Comment by dimix000** [comment]
update : after trying with the old version from the tutorial, the rescan file appears but later another bug happens

**Comment by chris-belcher** [comment]
A separate rescan script doesnt exist anymore, it is now a command line option of the main application.

`electrum-personal-server --rescan /path/to/config.ini`

Downgrading isnt a good idea, as you miss out on bug fixes and new features.

Which tutorial are you reading? It must be out of date.

**Comment by dimix000** [comment]
I was using this tutorial : https://driftwoodpalace.github.io/Hodl-Guide/hodl-guide_64_eps-mac.html#download-the-installation-package

For the command line option, I can not understand how to use it on a Mac. 
When double-clicking on electrum-personal-server in the bin folder, I get the following message in terminal "electrum-personal-server: error: the following arguments are required: config_file". 
How can I give the instruction of starting the server or to make a rescan, on a Mac? 

Thank you so much, I am breaking my head on this issue, windows install was much easier.

**Comment by chris-belcher** [comment]
Sorry I don't know, I've never really used a Mac.

**Comment by dimix000** [comment]
I am really stuck, is there a Mac use that could help ? 

I tried the following to run the rescan script : 

In terminal, in the python folder :

1. open ./electrum-personal-server --rescan --> gives me "unrecognised option"
2. open ./electrum-personal-server -h  --> gives me "Warning: Xcode platforms folder not found at "/Library/Developer/CommandLineTools". You may have invalid DEVELOPER_DIR"
3. open ./electrum-personal-server -h /Users/MyMAc/Library/Python/3.8/bin/config.ini --> gives me again "Warning: Xcode platforms folder not found at "/Library/Developer/CommandLineTools". You may have invalid DEVELOPER_DIR"

I will continue to try to find a solution but slowly giving up on electrum personal server on Mac
