### ISSUE TITLE
Unable to connect EPS with Electrum - EPS not listening for wallet

### ISSUE THREAD

**Issue by flying-dutchie** [chris-belcher/electrum-personal-server#268]
I'm trying to set up my own full node using Bitcoin Core, Electrum Personal Server (EPS) and Electrum Wallet, temporarily using a dummy wallet (wallet_1, which is why I didn’t bother hiding the key in Att. 3).

I'm by no means a computer expert, but just a slightly-more-than-average user of a Windows desktop computer. I know very little about networking protocols etc., and that's where I get stuck (I think).

I'm running everything from the same Windows desktop computer (not my main computer), using Windows 10, 64-bit.

I’m running Electrum v4.1.5, EPS v.0.2.3, and Bitcoin Core v.22.0.0.

However, I'm unsuccessful in making the connection between Electrum Wallet and EPS. I have searched the Internet looking for solutions, tutorials etc., but so far w/o success. I'm not getting the green button in the right lower corner of Electrum when using localhost:50002:s as the server.

In the command line of the Electrum shortcut I added the following behind the pathname: --oneserver --server localhost:50002:s.

Similarly, in the shortcut of EPS I added the path of the config.ini file to that of EPS.

Bitcoin Core is working fine. I'm using Tor to connect to the Internet, by making the necessary specifications in the bitcoin.conf file. 

![Att  1 - Bitcoin conf](https://user-images.githubusercontent.com/105047246/167117756-6d0d08ed-25e9-4289-98d6-9eaceaba9680.jpg)

I also made the necessary adjustments to connect with EPS. I’m running with Tor deamon service in the background. I have also tried to run it w/o Tor, but that didn’t work either.

As far as I can judge, EPS is also working fine. I have included the config.ini file for reference. 

![Att  2 - EPS config ini](https://user-images.githubusercontent.com/105047246/167117819-bc80a801-4414-4b08-81f7-922105e14914.jpg)

The only weird thing I noticed was that EPS is not “Listening for the Wallet”, as I believe must be the case? I have included a screen dump of the cmd-screen of EPS. When I press a key, EPS will be aborted. I also don't see any transactions being loaded.

![Att  3 - EPS cmd screen](https://user-images.githubusercontent.com/105047246/167117838-06fda440-e125-4edb-a226-b3d3a4db8ceb.jpg)

However, I can connect to external servers in Electrum, e.g. when I tick the box 'Select server automatically'. I then get the green button. When I then tick the box 'Use Tor proxy at port 9050' the button turns blue (which is also OK).

I also checked that my router ports are open, and I even disabled my firewall, but nothing seems to work. 

I typically use the following sequence: first I start Bitcoin Core (no issues), then I run the Electrum wallet, finally followed by EPS.

What am I doing wrong? Any help is much appreciated.

**Comment by strangebit** [comment]
My first thought is that it could have something to do with using `wallet_filename=electrumpersonalserver` in `config.ini` without also using `wallet=electrumpersonalserver` in `bitcoin.conf` (or `-wallet` command-line).

Sorry if that doesn't help. Might also help to run with `log_level_stdout = DEBUG` for more detailed logging output.

**Comment by flying-dutchie** [comment]
You may me right about this. During some earlier connection attempts I had this command (i.e. _wallet = electronpersonalserver_)  in bitcoin.conf, but then always got a warning message when starting Bitcoin Core. I have reinstated it again, and the warning is still there, see below:

![Message](https://user-images.githubusercontent.com/105047246/167253976-2fccd122-635a-4439-88e0-9953a0c7b3aa.jpg)

Apparently there is a duplicate wallet name somewhere. when Bitcoin Core is up and running the wallet screen shown is named _electrumpersonalserver_. 
Apparently Bitcoin Core uses this name even when it is not specified in the bitcoin.conf file. I have no idea why or how this happens, or how to fix this.

**Comment by strangebit** [comment]
>Apparently Bitcoin Core uses this name even when it is not specified in the bitcoin.conf file. I have no idea why or how this happens, or how to fix this.

I think it'll be because it's being stored in `settings.json` and then loaded on startup from there. If so ignore me then I think.

> when Bitcoin Core is up and running the wallet screen shown is named electrumpersonalserver.

My guess is your issue probably isn't related to this then. If Bitcoin Core is loading this wallet file then I think it should be fine with respect to that. In which case I'm still not sure what the actual problem is.

**Comment by flying-dutchie** [comment]
I checked the _settings.json_ file, but there's nothing to see there:

![Settings json file](https://user-images.githubusercontent.com/105047246/167257944-e5e83aad-cc0c-4383-987b-aa4cf0bf9c23.jpg)

Maybe it's indeed some other issue unrelated to this. Really puzzling....

Anyway, thx for trying to help. Much appreciated.
Let's hope someone else has a hunch.

**Comment by ohwussup** [comment]
Did you solve this issue?  I'm having a very similar issue and I can't solve it.  At this point it should say "Listening for Electrum Wallet"  But Mine just shows exactly like yours where it just says press any key to continue

**Comment by flying-dutchie** [comment]
Unfortunately not. Pls. let me know when you have solved it.

**Comment by ohwussup** [comment]
Will do and please do the same if you do.

Are you running any other wallet software with Bitcoin Core in the mean time?

**Comment by flying-dutchie** [comment]
No, except that I tried the test version of Bitcoin Core. The strange thing was that it failed to run. I’m not behind my computer now, but I will show you later what happened.

**Comment by andrewtoth** [comment]
@flying-dutchie it seems something went wrong with your wallet configuration. Without risking removing any of the wallets you created, you can run `bitcoin-cli createwallet electrumpersonalserver-new true true "" false false true` and then set `wallet_filename = electrumpersonalserver-new` in your EPS config.ini.

**Comment by flying-dutchie** [comment]
Andrew, thx for joining this discussion and trying to help. I'm not sure what you mean exactly with the "run" command. Do you mean in the Bitcoin Core console?
I tried that, but it came back with the following error:
![Error message](https://user-images.githubusercontent.com/105047246/172709081-bdcaeedf-ca6c-4f6e-945a-532c0b3152b9.jpg)

**Comment by andrewtoth** [comment]
Ahh... Yes in the console paste the command but remove `bitcoin-cli`.

**Comment by flying-dutchie** [comment]
The command worked fine this time, but after renaming the wallet in the config.ini file I still got the warning "Ignoring duplicate -wallet electrumpersonalserver" after restarting Bitcoin Core.
I then also changed the walletname in the bitcoin.conf file to electrumpersonalserver-new and again restarted Bitcoin Core. It still came back with the same warning, but now for 'electrumpersonalserver-new'.
When running EPS, it seems to import the new wallet and it shut down after pressing any key. Again it didn't say anything about listening for a wallet, but it came back with the same old 'Press any key to continue...'.
I reran EPS again, and to by big surprise it worked!
I now finally got the green button in Electrum!!

You finally solved my main issue. Thx a lot.

I'm still puzzled though why I get the warning when starting Bitcoin Core. Any clues would be highly appreciated.

**Comment by flying-dutchie** [comment]
I continued trying a few things, i.e.:
I disabled the command _wallet = electrumpersonalserver-new_ in bitcoin.config, which made the warning disappear, while still allowing me to connect EPS with Bitcoin Core :-)
I then added my real hardware wallet to Electrum, and and the connection still works.
This resolves all my issues.
Andrew, thx a lot again for your input.

**Comment by ptoscan** [comment]
I was having the same problem.
For me, the solution was to create a wallet on Core with the name "electrumpersonalserver" and with the encryption option disabled

![bitcoin_core_creating_wallet](https://user-images.githubusercontent.com/107663555/174218452-97ee808a-0a63-452e-a45f-be5e820c4baf.png)

*In "config.ini":
[bitcoin-rpc]
host = 127.0.0.1
port = 8332
datadir = E:\BitcoinCore
wallet_filename = electrumpersonalserver
poll_interval_listening = 30
poll_interval_connected = 1
initial_import_count = 1000
gap_limit = 25


*In "bitcoin.conf":
server=1
wallet=electrumpersonalserver


I hope it helps! :)
