### ISSUE TITLE
Electrum 3.2 subscribes to raw block headers

### ISSUE THREAD

**Issue by jleute** [chris-belcher/electrum-personal-server#34]
The newest version of Electrum subscribes to raw headers and is not compatible with electrum-personal-server.
Here is the corresponding Electrum pull request:
https://github.com/spesmilo/electrum/pull/4402/files

blockchain.headers.subscribe with raw=False is deprecated:
https://github.com/kyuupichan/electrumx/blob/master/docs/protocol-methods.rst

> Running Electrum 3.2 with electrum-personal-server results in the following error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/electrum/util.py", line 856, in run_with_except_hook
>     run_original(*args2, **kwargs2)
>   File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 1040, in run
>     self.wait_on_sockets()
>   File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 1022, in wait_on_sockets
>     self.process_responses(interface)
>   File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 689, in process_responses
>     self.process_response(interface, response, callbacks)
>   File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 594, in process_response
>     self.on_notify_header(interface, result)
>   File "/usr/local/lib/python3.6/dist-packages/electrum/network.py", line 1048, in on_notify_header
>     header_hex, height = header_dict['hex'], header_dict['height']
> KeyError: 'hex'

**Comment by chris-belcher** [comment]
Thanks. Fix incoming.

**Comment by SomberNight** [comment]
I tried to change the client to fallback to the old header subs format, but [blockchain.block.headers](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-block-headers) is also missing
see https://github.com/spesmilo/electrum/issues/4478

**Comment by chris-belcher** [comment]
Commits https://github.com/chris-belcher/electrum-personal-server/commit/4db135474f27d9b8888e74e766a7b1f84fff6c2f and https://github.com/chris-belcher/electrum-personal-server/commit/a66f5288d82aab16d45c0d85578ede1c1a09b4b3 should add implementations of the missing methods.

It works for my testnet node. Correctly subscribes to block headers and sends updates. Correctly replies to `blockchain.block.headers`. Currently waiting for my mainnet node to catch up to try it there too.

I'll make a new release soon. Hopefully someone else can try it too before then.

**Comment by suvayu** [comment]
I tried with my mainnet node, seems to work.

**Comment by kev-vl** [comment]
Works on my mainnet node w/ Electrum 3.2.2.

**Comment by pik0r** [comment]
Works! Thanks.
