### ISSUE TITLE
Support for BIP 49 and in general p2sh-p2wpkh

### ISSUE THREAD

**Issue by gabridome** [chris-belcher/electrum-personal-server#37]
I haven't found the way. If one derives the keys in a way to obtain those kind of addresses of also bech32, Ii is not documented how to do it in electrum-personal-server. 

There is a proposal Pieter Wuille is working on (https://gist.github.com/sipa/e3d23d498c430bb601c5bca83523fa82) that seams to be related to how Electrum and other wallets could deal with these kind of issues. This could be related also with #27 because the scantxoutset proposal will probably take into account that.

**Comment by chris-belcher** [comment]
Hopefully I've understood your question right.

In Electrum and Electrum Personal Server, master public keys that start with `ypub` or `upub` will produce p2sh-p2wpkh addresses. So add those to the config file and it should work.

It's not documented in Electrum Personal Server, but it is in Electrum: https://github.com/spesmilo/electrum-docs/blob/master/xpub_version_bytes.rst

**Comment by gabridome** [comment]
Ah yeah! I read something about it. I'll try. 
Thank you!
