### ISSUE TITLE
Gracefully handle Bitcoin Core shutdown

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#39]
When I quit Bitcoin Core server.py crashes:

```
    repr(exc))
electrumpersonalserver.jsonrpc.JsonRpcConnectionError: JSON-RPC connection failed. Err:ConnectionRefusedError(61, 'Connection refused')
```

It would be nice if instead it just turned off the Electrum server. That way the Electrum wallet would just show a red dot indicating it can't connect, which should be enough to remind me to start Bitcoin Core (though passing a more specific message to the wallet frontend would be nice too).

The other way around does work: if Bitcoin Core isn't running yet, the script starts and as soon as it can reach the RPC it boots up the server.

**Comment by chris-belcher** [comment]
Implemented by https://github.com/chris-belcher/electrum-personal-server/commit/dce6bff4768756c4ac2b0856d29ff9fe08348a15
