### ISSUE TITLE
Make EPS installable with pip

### ISSUE THREAD

**Issue by suvayu** [chris-belcher/electrum-personal-server#40]
While reviewing #38 it struck me, most of the rough edges are because EPS does not use `setuptools`, and isn't installable with `pip`.  I'm guessing since EPS isn't completely matured yet, simply no one has gotten around to addressing mundane issues like this?

**Comment by chris-belcher** [comment]
> I'm guessing since EPS isn't completely matured yet, simply no one has gotten around to addressing mundane issues like this?

Yes.
