### ISSUE TITLE
Use createwallet RPC with disable_private_keys

### ISSUE THREAD

**Issue by Sjors** [chris-belcher/electrum-personal-server#41]
If all goes well Bitcoin Core v0.17 ships with a new `createwallet` RPC that takes a `disable_private_keys`, which ensures the wallet will remain watch-only.

You could recommend that command in the README, or the script could just create a fresh wallet `electrum-personal-server-wallet.dat` if no wallet is explicitly configured.

**Comment by chris-belcher** [comment]
A PR doing this has been merged, closing.
