### ISSUE TITLE
Rescan progress indicator

### ISSUE THREAD

**Issue by MrHash** [chris-belcher/electrum-personal-server#43]
Would be nice to have some indication of rescan progress, say for example a message every 500 or 1000 blocks.

**Comment by chris-belcher** [comment]
That's outside the control of Electrum Personal Server, which only calls the `rescanblockchain` RPC call.

To get such a progress indicator look in the bitcoin node's `debug.log` file. (On linux run `tail -f debug.log`). Or if you're running bitcoin-qt then a dialog box will pop up.

**Comment by MrHash** [comment]
ok understood. thanks
