### ISSUE TITLE
Server socket address already in use

### ISSUE THREAD

**Issue by ramses2506** [chris-belcher/electrum-personal-server#45]
Hi Chris, thanks for your great work!

I have the issue that my hardware wallet produced a zpub key instead of a xpub key when I set it up. It seems that EPS/Electrum cannot read my public keys out of the zpub when I start ./rescan-script.py; it's not showing any transactions/keys. Is there a solution for this?

Thanks in advance!

**Comment by chris-belcher** [comment]
The only master public keys that work are obtained from Electrum's menu `Wallet` -> `Information. Master public keys created by the hardware wallet interface itself won't work.

So the workflow for hardware wallet + Electrum + EPS is: 1) Connect hardware wallet to Electrum 2) Obtain master public key(s) from Electrum's menu 3) Set up Electrum Personal Server

**Comment by ramses2506** [comment]
thanks for your reply. I understood that, but the master public key obtained from Wallet -> Information starts with "zpub.." and when I enter that zpub key into the eps config.cfg and $ ./server.py I get the following:

2018-08-16 21:22:53,700001 [  LOG] Obtaining bitcoin addresses to monitor . . .
2018-08-16 21:23:08,667017 [  LOG] Obtained list of addresses to monitor in 14.966687679290771sec
2018-08-16 21:23:08,667776 [  LOG] Building history with 200 addresses . . .
2018-08-16 21:23:08,765173 [  LOG] Found 0 txes. History built in 0.01688981056213379sec
2018-08-16 21:23:08,766883 [  LOG] Starting electrum server
Traceback (most recent call last):
  File "./server.py", line 559, in <module>
    main()
  File "./server.py", line 556, in main
    poll_interval_listening, poll_interval_connected, certfile, keyfile)
  File "./server.py", line 326, in run_electrum_server
    server_sock = create_server_socket(hostport)
  File "./server.py", line 318, in create_server_socket
    server_sock.bind(hostport)
OSError: [Errno 98] Address already in use

I'm assuming this error comes up because I have a zpub instead of an xpub, is that possible?

**Comment by chris-belcher** [comment]
That's nothing to do with the master public key, it's to do with how the server socket sometimes remains open for a short while. So if you close and restart EPS shortly after then it may crash with that error message. See this article for a longer explaination https://hea-www.harvard.edu/~fine/Tech/addrinuse.html

To fix/work around it, just wait a little bit long between closing and restarting EPS.

**Comment by ramses2506** [comment]
Hmm I get this Error also when I reboot and start EPS for the first time so I assume it has nothing to do with closing/restarting EPS too quickly..it seems the address is constantly in use. Can you think of another conflict/solution? Otherwise thank you for trying to help!

**Comment by chris-belcher** [comment]
Restarting probably won't do much because the kernel will probably save the socket state and keep listening after the reboot. The only way is to wait really (I'll add an item to my todo list to see if theres anything else that can be done)

I suppose you could change ports. Change the port in config.cfg and in Electrum until the original port is released.

**Comment by ramses2506** [comment]
Hi Chris, I found the mistake (it has nothing to do with EPS): 

- in the past, when I tried to set up EPS the first time, I already automated EPS startup on my raspberry. I didn't realise this after I worked again on this so this is the reason why the address was "already in use" (i'm new to linux, so i don't always know what I'm doing, just trying to figure this out

- even if I hadn't automated the set up, I wouldn't have worked because I set up the electrum wallet wrong in the first place. I chose "native segwit" (which produces a zpub) as a script type and not p2wpkh-p2sh (ypub). The latter would have been the one I had to choose because my wallet set up with trezor relies on this ypub. So actually I added an empty master public key to EPS.

- After I looked up the ypub on the trezor wallet website, I added this one into the config file and now it's working!

Thanks!

**Comment by dawiepoolman** [comment]
hi guys

I got the same error today on a raspibolt setup.  version 0.2.4:

```
INFO:2023-08-10 07:31:27,343: Synchronizing mempool . . .
INFO:2023-08-10 07:35:22,078: Found 157076 mempool entries. Synchronized mempool in 234.73371529579163sec
Traceback (most recent call last):
  File "/home/bitcoin/.local/bin/electrum-personal-server", line 8, in <module>
    sys.exit(main())
  File "/home/bitcoin/.local/lib/python3.9/site-packages/electrumpersonalserver/server/common.py", line 494, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/bitcoin/.local/lib/python3.9/site-packages/electrumpersonalserver/server/common.py", line 129, in run_electrum_server
    server_sock = create_server_socket(hostport)
  File "/home/bitcoin/.local/lib/python3.9/site-packages/electrumpersonalserver/server/common.py", line 82, in create_server_socket
    server_sock.bind(hostport)
OSError: [Errno 98] Address already in use
```

**Comment by dawiepoolman** [comment]
ah, nevermind.  it was a port conflict.  I changed it to listen on 50003 instead and now it works
