### ISSUE TITLE
blockchain.blocks.headers crashes the server

### ISSUE THREAD

**Issue by benma** [chris-belcher/electrum-personal-server#49]
Hi

When requesting headers with a start height and a count which reaches beyond the current tip, the server crashes. It should instead return the actual available number of headers that can be returned, as documented here:

https://github.com/kyuupichan/electrumx/blob/eb5c55107aa2da42365f2a93f6d8e689b92aabbe/docs/protocol-methods.rst#blockchainblockheaders

Stacktrace:

```
Traceback (most recent call last):
  File "./server.py", line 559, in <module>
    main()
  File "./server.py", line 556, in main
    poll_interval_listening, poll_interval_connected, certfile, keyfile)
  File "./server.py", line 364, in run_electrum_server
    txmonitor)
  File "./server.py", line 179, in handle_query
    headers_hex, n = get_block_headers_hex(rpc, start_height, count)
  File "./server.py", line 297, in get_block_headers_hex
    the_hash = rpc.call("getblockhash", [start_height])
  File "./electrumpersonalserver/jsonrpc.py", line 59, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.jsonrpc.JsonRpcError: {'code': -8, 'message': 'Block height out of range'}
```

**Comment by chris-belcher** [comment]
Thanks. Fix incoming.

**Comment by benma** [comment]
I was using bitcoin-0.16.1.

**Comment by chris-belcher** [comment]
Thanks.

I just checked out and compiled the master branch of bitcoin core, and still didn't reproduce it, so there was no change in behaviour.

I realize now the crash only happens when the `start_height` itself is beyond the blockchain height. If the `start_height` is less and `count` causes it to overrun then it wont crash. So this would happen only rarely. I know enough to fix it now.

**Comment by chris-belcher** [comment]
Hopefully fixed

**Comment by benma** [comment]
Just wrote the same patch more or less before I saw you fixed it. That was exactly it, two issues (starting out of range, and returned a float instead of an int). Thanks!
