### ISSUE TITLE
after double spend server.py cannot start

### ISSUE THREAD

**Issue by 0xbytes** [chris-belcher/electrum-personal-server#5]
After a double spend, server.py produces
20:49:21,991456 [  LOG] Building history with 3600 addresses
Traceback (most recent call last):
  File "./server.py", line 464, in <module>
    main()
  File "./server.py", line 450, in main
    if not txmonitor.build_address_history(relevant_spks_addrs):
  File "/home/kid/Projects/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 140, in build_address_history
    new_history_element = self.generate_new_history_element(tx, txd)
  File "/home/kid/Projects/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 215, in generate_new_history_element
    blockheader = self.rpc.call("getblockheader", [tx['blockhash']])
KeyError: 'blockhash'

================================================================
The problem is cleared up when:
1. delete ~/.bitcoin/wallet.dat
2. bitcoin-cli rescanblockchain 490000 (or any relevent block)
3. run ./server.py 
    21:01:35,874627 [  LOG] Importing 360 addresses in total
[0%]... [10%]... [20%]... [30%]... [40%]... [50%]... [60%]... [70%]... [80%]... [90%]... [100%]
21:03:15,973858 [  LOG] Importing done
21:03:15,974018 [  LOG] Done.
If recovering a wallet which already has existing transactions, then
run the rescan script. If you're confident that the wallets are new
and empty then there's no need to rescan, just restart this script
==================================================================

Looks OK. A better error reporting is needed to catch this error.

Keep up the awesome work. Thanks.

**Comment by chris-belcher** [comment]
Thanks for the issue.

So this is happening when there's two conflicting transactions, when one of them confirms? The other one can now never confirm.

Here in the code it checks whether "confirmations" == 0 https://github.com/chris-belcher/electrum-personal-server/blob/master/electrumpersonalserver/transactionmonitor.py#L191

Invalid transaction will I think put the "confirmations" to be -1 ?

How did you get a double-spend situation to happen? I'm guessing you used RBF to fee-bump. If so I can try that on testnet and recode that part to fix this.

**Comment by 0xbytes** [comment]
Note: I use trezor with electrum.
I send a transaction with a very low fee (0.4 sat / byte) thru the personal electrum server. The mem pool was between 50Kb to 800Kb for an hour. During that hour 10 blocks were mined. None of the blocks included my transaction. My node had the transaction as unconfirmed. I checked several block explorer and noticed that it did not have the transaction. This means that the transaction was not being propagated across the network by nodes because of the low fee. I decided to double spend by using the Trezor wallet thru Chrome. The double spend occured because the Trezor wallet did not see the electrum transaction as well. The Trezor wallet confirmed the transaction on the next block with 1 sat / byte fee.

**Comment by chris-belcher** [comment]
Thanks for the report of this rare situation. So the first transaction ended up conflicted in your situation. I figured out exactly how Electrum handles conflicted transactions, and it just ignores/drops them basically. So this commit does that. https://github.com/chris-belcher/electrum-personal-server/commit/584002a1643e3366ff8ea36258f54746e3906b95

**Comment by chris-belcher** [comment]
New release includes this bugfix.
