### ISSUE TITLE
address scripthash not known to server

### ISSUE THREAD

**Issue by coinsmith** [chris-belcher/electrum-personal-server#55]
Hi, I'm having a bit of a puzzle with the title notice in the terminal output. 

Clean config.cfg with 1 electrum wallet
run server.py to import addresses
run rescan script
run server.py again,

Then, "address scripthash not known to server" pops up in blocks of 26 lines. I'm a bit at a loss to get rid of this. Am I missing something?

**Comment by robust-cuttlefish** [comment]
I see this all the time, and it still works OK. Scripthash would seem to indicate a pay-2-script-hash address, meaning either a script such as multisig, or a backwards-compatible P2SH-wrapped witness-pubkey-hash.

Electrum personal server works fine anyway, it's probably not a problem.

**Comment by chris-belcher** [comment]
This error message means that your Electrum wallet requested addresses that were not known to Electrum Personal Server.

How many addresses has your wallet generated @coinsmith (in other words, how many payments has your wallet received). The default value for `initial_import_count` in config.cfg is 100, so if you have more than that then it would cause this.

`scripthash` in Electrum's protocol refers to `sha256(scriptPubKey)`, so it's basically interchangable with "address". So if you're missing some then it's actually quite bad, the server could inadvertently lie by omission.

**Comment by coinsmith** [comment]
My bad, the prefix for pubkeys in config.cfg of multisig wallets needs to be the amount of needed signatories, not the amount of keys. Closing.

**Comment by chris-belcher** [comment]
Having more than a hundred explains it. To fix the problem, increase the value of `initial_import_count` in your config.cfg file and then run `server.py` to import more addresses, rescan script then `server.py` again.

I'm going to improve the documentation about this so this can be more easily solved by others.

**Comment by chris-belcher** [comment]
ok so it actually was the signatures-required number. One thing that could be done is have the server print out the first 3 receive addresses of each wallet, so such mistakes might be slightly more obvious.

**Comment by coinsmith** [comment]
Hm, that could clarify things for people such as myself. When I look at the config.cfg *now* and see 'number of required signatories', it should have been self explanatory. Again, my bad.

**Comment by chris-belcher** [comment]
Dealt with the stuff in this issue with the recent commits, closing.

**Comment by coinsmith** [comment]
Nice, thanks.
