### ISSUE TITLE
Wallet doesn't load properly

### ISSUE THREAD

**Issue by bilthon** [chris-belcher/electrum-personal-server#62]
Hello, I'm trying to use EPS but with not much luck. I'm running bitcoin core 1.6.3 on a mac os x environment.

I've tried running it both from the latest git commit as from the latest release (using the server.py directly).

I placed my public master key in the `config.cfg` file and I had to increase the `initial_import_count` to 800 since this is a used wallet.

After that it took a while to index all addresses and it ran as expected. Except that when I open electrum `3.2.3` and connect to it, some information like the height at the "Coins" section and the total balance itself don't show up correctly.

All the coins show up with height -2 like this:

![screen shot 2018-10-29 at 5 43 22 pm](https://user-images.githubusercontent.com/1840721/47685135-6bd3e080-dba3-11e8-8e4f-ee3bb712e76e.png)

And well, the balance is just unconfirmed.

![screen shot 2018-10-29 at 5 42 59 pm](https://user-images.githubusercontent.com/1840721/47685128-64143c00-dba3-11e8-9ceb-fd5bb9b91c4a.png)

What other information can I provide that might help to diagnose what's happening here?

**Comment by chris-belcher** [comment]
Thanks for the issue.

I doubt rescan will fix it but its worth a try.

Do you have pruning enabled?

Are there any error messages being printed out?

Could you look in the debug file to see if theres any useful information. If not then if you're comfortable with it, edit your debug log file to remove all your addresses and transaction IDs, then encrypt it and email it to me, it might reveal what's going on.

**Comment by bilthon** [comment]
The rescan actually helped a bit. One of my wallets is completely synced, while the other one is more than half way synced. Weird, I know.

And no, I don't have pruning enabled and I'm not using bitcoin core for anything other than EPS at the moment. I did however specify 2 master public keys, that's why I'm reporting on 2 wallets at the same time.

What I also had to do is run both the release and the cloned version of the EPS. I first did a checkout and run the code from the latest commit. But then since the `rescan-script.py` file was nowhere to be found there I wend ahead and downloaded the `v0.1.5` release version.

**Comment by chris-belcher** [comment]
Interesting that it helped(!)

If it's only halfway sync'd then maybe increase `initial_import_count` more and then run the server again, and rescan again.

The master branch has a new way of installing which involves using pip, which is why the scripts don't work the same way.

What you've shown is only the stdout output. There's much more information in the debug log file which is called `debug.log` and is in the same directory as `server.py` (this is all assuming you're using the latest release rather than master)

**Comment by bilthon** [comment]
Ok I just tried the latest release `0.1.6` and this situation persist, but only with a specific wallet. I have 3 loaded:

1. An old non-segwit account
2. A newer, ledger enabled p2sh-wrapped segwit wallet
3. A newer still, ledger enabled segwit native wallet

The only one giving me problems now is the second one. And the most puzzling thing about it all is that only recent transactions, not old ones.

I'm starting to think that this could be a problem on the wallet side, or with this specific wallet instance.

**Comment by chris-belcher** [comment]
Were you able to look inside the debug log file? It records the process of building up the list of transactions, so there should be clues to why they appear with unconfirmed(?).

**Comment by bilthon** [comment]
Yes, I found the log file. But it is full of private tx info and it has more 16K lines! Is there something specific that you think I should look for? I can only find INFO and DEBUG logs, no ERROR or WARNING entries.

**Comment by chris-belcher** [comment]
Starting from the top of the file it will build up its own internal dict of all the transactions in your wallet. If you follow that line by line (hopefully its self-explainatory) then there might be a place where you see why some transactions didnt get added to the dict.

**Comment by bidelakbari** [comment]
It is kinda a necrobump since it is an old post. but for newcomers, can confirm double scanning will resolve the issue of not showing the current balance. although I did it with <code>electrum-personal-server-rescan</code> not the mentioned py script
