### ISSUE TITLE
"BUG! Not handling method blockchain.scripthash.get_balance"

### ISSUE THREAD

**Issue by weissjeffm** [chris-belcher/electrum-personal-server#68]
> 2018-11-08 21:01:07,017535 [  LOG] A transaction confirmed: [elided txid]
2018-11-09 11:15:23,336082 [  LOG] Electrum wallet disconnected
2018-11-09 11:15:33,279493 [  LOG] Electrum connected from ('192.168.1.72', 45994)
2018-11-09 11:18:17,269066 [  LOG] *** BUG! Not handling method: blockchain.scripthash.get_balance query={'method': 'blockchain.scripthash.get_balance', 'params': ['elided txid'], 'id': 83}
2018-11-09 11:18:27,330288 [  LOG] Electrum wallet disconnected
2018-11-09 11:18:27,539484 [  LOG] Electrum connected from ('192.168.1.72', 46090)

This is occurring with a tx that appears as "unconfirmed parent" in electrum (and indeed it was a tx with an unconfirmed parent, but both the parent and child are now confirmed but EPS apparently is choking on it somehow).

**Comment by weissjeffm** [comment]
Thanks, restarting EPS does get it to show as confirmed.

**Comment by weissjeffm** [comment]
I actually can't be sure the error in the log is directly related to the unconfirmed parent TX, but EPS had been working flawlessly for months up until that tx arrived, so it would be a coincidence if the log error wasn't related.

**Comment by weissjeffm** [comment]
Electrum 3.2.3, Linux

**Comment by chris-belcher** [comment]
I haven't been able to reproduce this on testnet by having a transaction with an unconfirmed parent sent to my test wallet. If you still have the debug log file, could you look inside and see if there's anything unusual which might give clues.

I can implement the method `blockchain.scripthash.get_balance` which should fix it, but it would be interesting to see the bug in action.

**Comment by chris-belcher** [comment]
Method implemented here https://github.com/chris-belcher/electrum-personal-server/commit/dcbbf60f42b0477e38b868bcefe37948f33e7a37 Obviously I haven't been able to try it with Electrum wallet.

Closing this issue for now, if we get more information on the bug then it can be reopened.
