### ISSUE TITLE
Confusing readme with respect to server start

### ISSUE THREAD

**Issue by SteffenIvanhoe** [chris-belcher/electrum-personal-server#69]
After installing the server with pip3 your instructions continue with 

> Run electrum-personal-server /path/to/config.cfg to start Electrum Personal Server.

There is no "electrum-personal-server.exe" or something similar on my Windows PC. I have no idea where to find and how to start the server. That should be detailed some more to understand it.

I'm not a Python user but I also tried the command "python electrumpersonalserver" because it obviously might be in this directory but got the error message "can't find '__main__' module in 'electrumpersonalserver'".

The readme gives me no idea how to proceed at this point.

**Comment by chris-belcher** [comment]
Thanks for the issue.

I'm not a Windows user so unfortunately I don't know how to help you, except to highlight @TychoVrahe who uses EPS on Windows and might have some advice.

**Comment by SteffenIvanhoe** [comment]
I was able to solve this. A full disk search found the exe file in the directory "C:\Users\Steffen\AppData\Roaming\Python\Python37\Scripts". Might be worth it to add a hint to the readme for non-Python people. I will close this issue.

**Comment by chris-belcher** [comment]
So are you saying it doesn't add that to %path% ? which means you can't just run "electrum-personal-server" on CLI anywhere?

**Comment by SteffenIvanhoe** [comment]
I have just checked the path. What is added is "C:\Users\Steffen\AppData\Local\Python\Python37\Scripts"! This is the wrong addition because the directory is not "Local" but "Roaming". The "...\Local\Python\Python37\Scripts" directory does not even get created. This seems to be a bug in the Python installer ...?

**Comment by chris-belcher** [comment]
That's odd.

When I get the chance I'll try it in a VM and see if there's anything I can edit.

In the medium term I'd like to use pyinstaller to do this: https://github.com/chris-belcher/electrum-personal-server/issues/63#issuecomment-435919552 and then windows users won't need to install anything but just run an exe.

Reopening the issue because this is an unsolved bug.

**Comment by chris-belcher** [comment]
Not an issue now that we've been using pyinstaller
