### ISSUE TITLE
Wallet Notify

### ISSUE THREAD

**Issue by RutNai** [chris-belcher/electrum-personal-server#72]
Would be nice if each [master-public-keys] can run notify script.
Basically like bitcoind walletnotify but with multiple wallets.

config.cfg
``` 
[master-public-keys]
any_name_works = xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF
any_name_works2 = xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF

[wallet-notify]
any_name_works = path/to/notify-script %s
any_name_works2 = path/to/notify-script2 %s
```

**Comment by chris-belcher** [comment]
Is there a benefit to doing this over having scripts talk to Electrum wallet? That way the scripts will still work even if Electrum uses another server that isnt EPS.

**Comment by RutNai** [comment]
Benefit would be that it run on server and always on.

Another approach to this is
if EPS add label to watch-only addresses in bitcoind using the name in config.cfg instead of "electrum-watchonly-addresses".
With information from label bitcoind walletnotify can than determine which script to run.

**Comment by chris-belcher** [comment]
I must be missing something. Why can't a notify script use the label "electrum-watchonly-addresses" ? As far as I know bitcoind's walletnotify is invoked for all txes and can't be made to behave differently with different labels.

**Comment by RutNai** [comment]
Right now all addresses group together with label "electrum-watchonly-addresses".

If each wallets are label differently than
bitcoind walletnotify script can be like this
```
if(label == any_name_works) {
  run path/to/notify-script %s
}else if(label == any_name_works2){
  run path/to/notify-script2 %s
}
```

**Comment by chris-belcher** [comment]
I think I'm against this change on the basis of avoiding feature creep. Since this feature to not directly related to EPS as a server for Electrum. Happy to be convinced otherwise though.

I'd say users who want this feature should edit the EPS source files themselves.
