### ISSUE TITLE
Missing dependencies in README

### ISSUE THREAD

**Issue by andrewtoth** [chris-belcher/electrum-personal-server#73]
I just installed the wallet on a new machine, and when running `pip3 install --user .` it gave an error  `error: invalid command 'bdist_wheel'`. I had to search to find out I needed to run `pip3 install wheel` first. I did this on Linux after installing Electrum, so I had already installed the dependencies for that. I'm not sure what needs to be run on Windows or Mac for an install on a fresh machine either. These should probably be documented in the readme.

Also, after installing the `electrum-personal-server` command was not available. I had to run `~/.local/bin/electrum-personal-server config.cfg`. Is there a workaround to getting that available in global path right after install? Should also be documented in the readme.

**Comment by chris-belcher** [comment]
Thanks for the issue.

I looked up what wheel is. A note can be added.

As for having `~/.local/bin/`, I don't know sorry. I guess some linux distributions don't have this added to the path by default. I can add a note about that to readme as well.

**Comment by andcoisqu** [comment]
There must be a command to update `~/.local/bin/` to the path, because after reboot it was added just fine.

**Comment by andrewtoth** [comment]
Oops posted from my work computer. 

There must be a command to update ~/.local/bin/ to the path, because after reboot it was added just fine.

**Comment by andrewtoth** [comment]
Linux Mint
