### ISSUE TITLE
FreeBSD rc.d startup script

### ISSUE THREAD

**Issue by seth586** [chris-belcher/electrum-personal-server#77]
Works after running the following at the comamnd line:
`/root/.local/bin/electrum-personal-server /root/eps-v0.1.6/config.cfg
`
I attempted to make a startup script in /etc/rc.d/electrumpersonalserver:
```
#!/bin/sh
. /etc/rc.subr

name=electrumpersonalserver
rcvar=electrumpersonalserver_enable
command=/root/.local/bin/electrum-personal-server
command_args=/root/eps-v0.1.6/config.cfg
command_interpreter=/usr/local/bin/python3.6
start_cmd="$command"

load_rc_config $name
run_rc_command "$1"
```
And I get the following error:
```
root@bitcoin_node:/etc/rc.d # service electrumpersonalserver.sh start
Traceback (most recent call last):
  File "/root/.local/bin/electrum-personal-server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'electrum-personal-server==0.1.4.dev0' distribution was not found and is required by the application
```
Any ideas?

**Comment by chris-belcher** [comment]
I wonder if its related to the bug that this PR fixed https://github.com/chris-belcher/electrum-personal-server/pull/74

**Comment by seth586** [comment]
I uninstalled, edited setup.py, and reinstalled, now this:
`root@bitcoin_node:/etc/rc.d # service electrumpersonalserver start
Traceback (most recent call last):
  File "/root/.local/bin/electrum-personal-server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'electrum-personal-server==0.1.6.dev0' distribution was not found and is required by the application
`

**Comment by suvayu** [comment]
Hi @seth586, I am the person who added pip support.

I think you are mixing two different kinds of installation.  If you are using the `--user` flag, you should do it as the regular user (not as `root`) and install it under the regular user's home, e.g. `/home/seth586/.local/bin/`, etc.  However I am guessing you want to run `electrum-personal-server` as `root` (not sure if that's necessary, or wise), and want to install it system-wide.  For that, you should install as `root`, **without** the `--user` flag.  Then everything will be installed with the rest of your python packages in `/usr/local/lib/python3.6/site-packages/`, and the scripts should end up in `/usr/local/bin/`.

Please let me know if this helps.

**Comment by seth586** [comment]
Thank you, that makes sense! It is running in an iocage jail, so I wasn't too concerned about root access.

**Comment by seth586** [comment]
As follow up, I tried installing as user 'bitcoin' with the --user flag, and works fine as user bitcoin. However, trying to daemonize as root fails with a similar error as before:
`# usr/sbin/daemon -u bitcoin /home/bitcoin/.local/bin/electrum-personal-server /home/bitcoin/electrum-personal-server/config.cfg`

**Comment by seth586** [comment]
Followup, I installed as user `bitcoin` with the `--user` flag. It runs fine as user `bitcoin`.

However, as user `root` daemonizing with `-u` flag set to `bitcoin` fails with a similar error in my original post:
`# /usr/sbin/daemon -u bitcoin /home/bitcoin/.local/bin/electrum-personal-server /home/bitcoin/electrum-personal-server/config.cfg`

This works as root:

`su bitcoin -c '/usr/sbin/daemon -f /home/bitcoin/.local/bin/electrum-personal-server /home/bitcoin/electrum-personal-server/config.cfg'
`
This is a working rc.d script:
```
#!/bin/sh
# REQUIRE: LOGIN cleanvar bitcoind

. /etc/rc.subr

name=electrumpersonalserver
rcvar=electrumpersonalserver_enable

pidfile="/home/bitcoin/electrum-personal-server/${name}.pid"
sig_stop=-KILL

start_cmd="${name}_start"
stop_cmd="${name}_stop"

electrumpersonalserver_start()
{
        su bitcoin -c '/usr/sbin/daemon -f -p \
        /home/bitcoin/electrum-personal-server/electrumpersonalserver.pid \
        /home/bitcoin/.local/bin/electrum-personal-server \
        /home/bitcoin/electrum-personal-server/config.cfg'
        if [ $? -ne 0 ]; then
                echo "Error starting ${name}."
                exit 1
        fi
    echo "Starting ${name}."
}

electrumpersonalserver_stop()
{
    echo "stopping ${name}"
    kill `cat ${pidfile}`
}

load_rc_config $name
run_rc_command "$1"
```

**Comment by suvayu** [comment]
> However, as user `root` daemonizing with `-u` flag set to `bitcoin` fails with a similar error in my original post:
> `# /usr/sbin/daemon -u bitcoin /home/bitcoin/.local/bin/electrum-personal-server /home/bitcoin/electrum-personal-server/config.cfg`
> 
> This works as root:
> 
> `su bitcoin -c '/usr/sbin/daemon -f /home/bitcoin/.local/bin/electrum-personal-server /home/bitcoin/electrum-personal-server/config.cfg' `

You are making a similar mistake again.  My guess is `daemon` does not create the environment of the user `bitcoin`.  It just runs EPS as the user `bitcoin`.  `su bitcoin` on the other hand is equivalent to loging in as the user `bitcoin` and invoking EPS, hence it works.

I would strongly recommend not mix two different setups, if you install as a regular user, run EPS as that user.  Instead if you want to run EPS as `root`, please install it as `root` (without the `--user` flag).

**Comment by seth586** [comment]
OK, installed as user root with command `pip-3.6 install .` and now I can run `daemon` with the flag `-u bitcoin` to run with that user's privileges. Thank you so much for helping me through this!

If anyone wants a rc.d startup script, this will work:
```
#!/bin/sh
#
# PROVIDE: electrumpersonalserver
# REQUIRE: bitcoind
# KEYWORD:

. /etc/rc.subr

name="electrumpersonalserver"
rcvar="electrumpersonalserver_enable"
electrumpersonalserver_command="/usr/local/bin/electrum-personal-server /electrum/config.cfg"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -u bitcoin -r -f ${electrumpersonalserver_command}"

load_rc_config $name
: ${electrumpersonalserver_enable:=no}

run_rc_command "$1"
```
