### ISSUE TITLE
Electrum won't sync anymore

### ISSUE THREAD

**Issue by otaviobps** [chris-belcher/electrum-personal-server#88]
I had EPS running fine for two days. Made an alias and let it running in background.

Today I opened Electrum and it won't sync anymore. I tried restarting EPS, but no luck. Here is the EPS log:

```
INFO:2019-02-15 15:06:32,305: Starting Electrum Personal Server
INFO:2019-02-15 15:06:32,305: Logging to /tmp/electrumpersonalserver.log
INFO:2019-02-15 15:06:32,703: Displaying first 3 addresses of each master public key:
INFO:2019-02-15 15:06:32,779: 
te_giro =>
	xxx
	xxx
	xxx
INFO:2019-02-15 15:06:32,818: 
psw =>
	xxx
	xxx
	xxx
INFO:2019-02-15 15:06:32,892: 
te_cold =>
	xxx
	xxx
	xxx
INFO:2019-02-15 15:06:32,936: 
te_recebe =>
	xxx
	xxx
	xxx
INFO:2019-02-15 15:06:32,936: Obtaining bitcoin addresses to monitor . . .
INFO:2019-02-15 15:08:54,439: Obtained list of addresses to monitor in 142.12532377243042sec
INFO:2019-02-15 15:08:54,440: Building history with 8000 addresses . . .
INFO:2019-02-15 15:08:58,099: Found 430 txes. History built in 2.6723499298095703sec
INFO:2019-02-15 15:08:59,749: Starting electrum server
INFO:2019-02-15 15:08:59,750: Listening for Electrum Wallet on ('0.0.0.0', 50002)
INFO:2019-02-15 15:09:05,498: Electrum connected from ('192.168.0.78', 51883)
INFO:2019-02-15 15:09:42,817: Electrum wallet disconnected
INFO:2019-02-15 15:09:43,165: Electrum connected from ('192.168.0.78', 51911)
INFO:2019-02-15 15:10:20,675: Electrum wallet disconnected
INFO:2019-02-15 15:10:20,907: Electrum connected from ('192.168.0.78', 51964)
INFO:2019-02-15 15:10:58,968: Electrum wallet disconnected
INFO:2019-02-15 15:10:59,233: Electrum connected from ('192.168.0.78', 51978)
ERROR:2019-02-15 15:11:40,511: IOError: BrokenPipeError(32, 'Broken pipe')
INFO:2019-02-15 15:15:02,836: Electrum connected from ('192.168.0.78', 52018)
INFO:2019-02-15 15:15:42,929: Electrum wallet disconnected
INFO:2019-02-15 15:15:43,242: Electrum connected from ('192.168.0.78', 52038)
INFO:2019-02-15 15:16:23,895: Electrum wallet disconnected
INFO:2019-02-15 15:16:24,210: Electrum connected from ('192.168.0.78', 52054)
```

Aparently, Electrum is disconnecting and reconnecting even if I don't close and reopen it. I was running Electrum 3.3.2, and then updated it to 3.3.4, but no luck

**Comment by chris-belcher** [comment]
Timeout is one thing to check:

Do you use the Electrum command line arguments `--oneserver` and `--server` ? If not try using them both, in the latest version of Electrum using both those arguments also greatly increases Electrum's internal timeouts.

**Comment by otaviobps** [comment]
I'm running Electrum on Mac. I didn't have issues connecting it before to my linux server, however I can't get it to sync anymore.

I didn't use the `--oneserver`, because when I try to open it with `open Electrum.app` I can't pass this flag. I'll have to figure it out.

Since I couldn't sync it with my server, I connected to a random Electrum server and made a tx. Should I rescan the wallet from the beginning?

**Comment by otaviobps** [comment]
Ok, I could open Electrum with `open Electrum.app --args --oneserver --server 192.168.0.115:50002:s` and it synced to my EPS. I didn't need to rescan my wallet because of the tx I made with a random server.

Probably was a timeout issue. Thanks

**Comment by chris-belcher** [comment]
Is that how command line arguments work in Mac OS ?

**Comment by otaviobps** [comment]
Yes, Electrum is a .app, so you have to use the `open` command, and to pass arguments to it you have to use it with `open Electrum.app --args` and pass the args.
