### ISSUE TITLE
Windows: electrum-personal-server' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by MrPaz** [chris-belcher/electrum-personal-server#92]
So I'm trying to put eps on a Windows 10 computer.  I've installed it on several Linux machines before following posted directions with no issue.  However, when following same directions for Windows, I'm seeing the following after install and attempting to run for the first time:
```
C: ...\electrum-personal-server-eps-v0.1.6>electrum-personal-server .\config.cfg
'electrum-personal-server' is not recognized as an internal or external command,
operable program or batch file.
```
So is this just a matter of adding eps to path?  If so, what exactly do I add to path?

Using latest version.  I've uninstalled and reinstalled several times.  Also, I don't think this matters, but bitcoin is installed in a non-standard location and this is a pruned node.

Thanks

**Comment by HelgeHunding** [comment]
I wrote a tutorial you can try here https://github.com/HelgeHunding/guides/blob/master/hodl-guide/hodl-guide_63_eps-win.md 

Let me know if something needs to be clarified. 

@chris-belcher if you find the time, would love if you could take a quick look at the tutorial so I don't say anything stupid in it!

**Comment by chris-belcher** [comment]
Thanks @HelgeHunding I'll look at it.

**Comment by kezown** [comment]
Really good tutorial @HelgeHunding, worked amazingly well for me.

**Comment by MrPaz** [comment]
@HelgeHunding thank you! adding the pause to the batch file allowed me to see the error message in cmd window before it closed, and I noticed my install put disablewallet=1.  *facepalm*  

Spent about an hour going through your guide too.  I'll look at it some more and let you know if I see anything to improve, but so far it's a really great resource.

**Comment by HelgeHunding** [comment]
Thanks guys! 

Cool, appreciate all feedback on the guide :) @MrPaz
