### ISSUE TITLE
RPC connection refused

### ISSUE THREAD

**Issue by Xaspr** [chris-belcher/electrum-personal-server#94]
Hi, any idea how to fix this error? 

After installing and running ~/.local/bin/electrum-personal-server on RockPro64 I get the following error: 

> INFO:2019-03-23 15:25:52,527: Starting Electrum Personal Server
> INFO:2019-03-23 15:25:52,528: Logging to /tmp/electrumpersonalserver.log
> ERROR:2019-03-23 15:25:52,535: Error with bitcoin json-rpc: JsonRpcConnectionError("JSON-RPC connection failed. Err:ConnectionRefusedError(111, 'Connection refused')",)

This setup below used to work on a Raspberry Pi, but now it doesn't work on a RockPro64. Bitcoin and LND are running well on the RockPro64 though. 
If i could just get EPS to work, that would be perfect. 

My bitcoin.conf looks like this: 

> server=1
> daemon=1
> testnet=0
> txindex=1
> deprecatedrpc=addwitnessaddress
> deprecatedrpc=signrawtransaction
> rpcuser=XXXXXX
> rpcpassword=XXXXXXX
> zmqpubrawblock=tcp://127.0.0.1:28332
> zmqpubrawtx=tcp://127.0.0.1:28333
> dbcache=100
> maxorphantx=10
> maxmempool=50
> maxconnections=40
> maxuploadtarget=5000
> proxy=127.0.0.1:9050
> bind=127.0.0.1
> listenonion=1
> onlynet=onion
> dnsseed=0
> dns=0
> addnode=nkf5e6b7pl4jfd4a.onion
> addnode=yu7sezmixhmyljn4.onion

Electrum config.cfg looks like this: 

> [master-public-keys]
> [watch-only-addresses]
> [bitcoin-rpc]
> host = 127.0.0.1
> port = 8332
> datadir =
> rpc_user = XXXXXX
> rpc_password = XXXXXX
> wallet_filename =
> poll_interval_listening = 30
> poll_interval_connected = 5
> initial_import_count = 1000
> gap_limit = 25
> [electrum-server]
> host = 0.0.0.0
> port = 50002
> ip_whitelist = *
> certfile = certs/cert.crt
> keyfile = certs/cert.key

**Comment by HelgeHunding** [comment]
I experienced this issue once. I solved it by changing to the "cookie method" (comment rpc_user and rpc_password in both files). That might not be an option if you are using LND. But you could try it for debugging. I guess you've triple checked the user and passwords in both files and that they don't contain `#`.

**Comment by Xaspr** [comment]
Thanks! After commenting these lines in both config files and restarting bitcoind, it does actually work. 

But this is just a work around for now, because I need the RPC user/pass for LND.
Any idea what the issue could be?

**Comment by HelgeHunding** [comment]
Yea, I figured that you needed that for LND.

Unfortunately, I never dug deeper once it was up and running. I had moved my Bitcoin directory and had two bitcoin.conf files and figured that maybe that was causing the issues. But from your files it looks like it is located at the standard directory. So, that shouldn't be the issue.

So sorry, can't help you there.

It's kind of weird because all the cookie method is a default username and a random password generated for you. So, shouldn't be much of a difference. You could try opening the cookie file with a text editor and use the password in there for your RPC_password to debug. Then it really shouldn't be any difference. The username for the cookie method is `__cookie__` I believe. So use that as user.

**Comment by Xaspr** [comment]
Thank you so much for your help. Great that I got EPS working now again, which for me is more important than LND at the moment. 

I'll follow up if I find out more.

**Comment by chris-belcher** [comment]
Try changing something else in your `bitcoin.conf` file to see whether the bitcoin node actually reads in that file. For example add `connect=0` and check where bitcoin really does not connect to any peer when restarted.

**Comment by Xaspr** [comment]
I thought the bitcoin.conf file was read, because it was running over Tor as was included in the conf file. But maybe changing bitcoin.conf by first commenting the RPC user/pass lines and changing it back later made the difference. 

But then, maybe it also had to do with my systemd setup for bitcoind.service. After doing sudo systemctl restart bitcoind , and restarting EPS, EPS did work correctly with RPC user/pass method. Only after restarting the RockPro64, it didn't work again. It seems to be that after changing the systemd setup for /etc/systemd/system/bitcoind.service it works all the time now.  

To clarify, first, I used the Thundroid startup config from the great guides from Stadicus, later on I used his Raspberry Pi (Raspibolt) bitcoind.service setup. I find it hard to figure out why this worked. Perhaps it was just changing something that already fixed it.

Anyway, here's the systemd files:  

First this /etc/systemd/system/bitcoind.service setup, which didn't work for me: 

> [Unit]
> Description=Bitcoin daemon
> After=network.target
> [Service]
> ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid
> RuntimeDirectory=bitcoind
> User=bitcoin
> Group=bitcoin
> Type=forking
> PIDFile=/run/bitcoind/bitcoind.pid
> Restart=on-failure
> PrivateTmp=true
> ProtectSystem=full
> NoNewPrivileges=true
> PrivateDevices=true
> MemoryDenyWriteExecute=true
> [Install]
> WantedBy=multi-user.target

Second systemd setup for bitcoind, which does work: 

> [Unit]
> Description=Bitcoin daemon
> After=network.target
> [Service]
> ExecStartPre=/bin/sh -c 'sleep 30'
> ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoin/bitcoind.pid
> PIDFile=/home/bitcoin/.bitcoin/bitcoind.pid
> User=bitcoin
> Group=bitcoin
> Type=forking
> KillMode=process
> Restart=always
> TimeoutSec=120
> RestartSec=30
> [Install]
> WantedBy=multi-user.target

It works great now. Maybe changing bitcoin.conf by first commenting the RPC user/pass and later removing the # again also made a difference. 

Many thanks for your help!

**Comment by Armantheparman** [comment]
> I experienced this issue once. I solved it by changing to the "cookie method" (comment rpc_user and rpc_password in both files). That might not be an option if you are using LND. But you could try it for debugging. I guess you've triple checked the user and passwords in both files and that they don't contain `#`.

Hi, I'm having the same problem. But when I comment out rpc and password, the cookie can not be found. Where is it supposed to be?
