### ISSUE TITLE
Electrum fails to sync

### ISSUE THREAD

**Issue by BobleChinois** [chris-belcher/electrum-personal-server#95]
Hi, I'm running EPS on Ubuntu 18.04, I used to run EPS 1.5 without issue, I've not been using it for some times and just upgraded to 1.6. 
I use Electrum3.3.4 on another Linux machine on my LAN, it can connect with EPS but then get stuck on "synchronizing" status.
I had a look at the log and I see many lines like this one : 
```DEBUG:2019-03-29 23:59:42,958: => {"jsonrpc": "2.0", "method": "blockchain.scripthash.subscribe", "id": 693, "params": ["1b6d5bc64e61f9177be4142653faXXX"]}```
Then it disconnect and connect again immediately, before getting stucked again, and then disconnect again...

**Comment by chris-belcher** [comment]
Thanks for the issue.

Do this: run electrum with the command line argument -v, then go the console and type `network.debug = True`. Then you should get lots of debug information on the command line. Hopefully that will provide more clues.

**Comment by BobleChinois** [comment]
Hi, I tried what you proposed, and here's the result : 
[electrum logging](https://gist.github.com/BobleChinois/22f6bcd091a2f7ccdfadc0ce47727dbd)
It seems to hang on with those lines : 
```
 (id: 3)
[i][192.168.1.22] --> bc1q5d8l0w33h65e2l5x7ty6wgnvkvlqcz0wfaslpz (id: 4)
[i][192.168.1.22] --> [] (id: 5)
[i][192.168.1.22] --> 1e-06 (id: 6)
```
and then restart after one minute or so.
After a couple of times, it changes slightly : 
```
[i][electrum5910158.elastics.info] <-- ('server.ping',) {} (id: 3)
[i][electrum5910158.elastics.info] --> None (id: 3)
[i][electrumx.bot.nu] <-- ('server.ping',) {} (id: 3)
[i][electrumx.bot.nu] --> None (id: 3)
[n] network: retrying connections
[i][electrum2.villocq.com] <-- ('server.ping',) {} (id: 6)
[i][electrumx.ftp.sh] <-- ('server.ping',) {} (id: 4)
[i][electrum2.villocq.com] --> None (id: 6)
[i][electrumx.ftp.sh] --> None (id: 4)
[i][kirsche.emzy.de] <-- ('server.ping',) {} (id: 4)
[i][kirsche.emzy.de] --> None (id: 4)
```
and get stuck like this.
I don't know if it makes sense to you, because it sure doesn't to me.

**Comment by BobleChinois** [comment]
I tried to reproduce the issue once more today, and it seems to work flawlessly now. 
I'm closing the issue and will open it again later if I can reproduce the issue at some point.
