### ISSUE TITLE
EPS only verifying 1 block at a time

### ISSUE THREAD

**Issue by Coinomatron** [chris-belcher/electrum-personal-server#97]
As stated in the title, it verifies 1 block at a time. I did a rescan of the last 1000 blocks, to no avail. System: Ubuntu 16.4, electrum 3.3.0, EPS, 

output of command line -v:

user@user:~/Downloads/Electrum-3.3.0$ python3.7 ./run_electrum --oneserver --server localhost:50003:s -v
[SimpleConfig] electrum directory /home/user/.electrum
failed to connect to JSON-RPC server: [Errno 111] Connection refused
[p] registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
[p] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[p] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[p] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[p] registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
[p] registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
[p] registering wallet type ('2fa', 'trustedcoin')
[profiler] Plugins.__init__ 0.0044
[n] blockchains [0]
[FxThread] using exchange BitcoinAverage
[n] starting network
[n] connecting to localhost:50003:s as new interface
[profiler] Daemon.__init__ 0.0025
[i][localhost] connection established. version: ['ElectrumPersonalServer 0.1.6', 1.4]
[i][localhost] set blockchain with height 570053
[i][localhost] can't connect 570068
[i][localhost] requesting block header 570054 in mode backward
[n] switching to localhost:50003:s
[i][localhost] exiting backward mode at 570054
[i][localhost] could connect 570054
[i][localhost] requesting chunk from height 570055
[profiler] ElectrumGui.__init__ 0.2143
[WalletStorage] wallet path /home/user/.electrum/wallets/electrumwallet
[profiler] Standard_Wallet.load_transactions 0.0006
[profiler] Standard_Wallet.load_local_history 0.0001
[profiler] Standard_Wallet.check_history 0.0001
[w][electrumwallet] internal address corruption test skipped due to missing libsecp256k1
[profiler] Standard_Wallet.try_detecting_internal_addresses_corruption 0.0001
[profiler] ElectrumWindow.load_wallet 0.1328
[i][localhost] disconnecting gracefully. Network request timed out.
[n] connecting to localhost:50003:s as new interface
[i][localhost] connection established. version: ['ElectrumPersonalServer 0.1.6', 1.4]
[i][localhost] set blockchain with height 570054
[i][localhost] can't connect 570068
[i][localhost] requesting block header 570055 in mode backward
[n] switching to localhost:50003:s
[i][localhost] exiting backward mode at 570055
[i][localhost] could connect 570055
[i][localhost] requesting chunk from height 570056
[n] network: retrying connections
[i][localhost] disconnecting gracefully. Network request timed out.
[n] connecting to localhost:50003:s as new interface
[i][localhost] connection established. version: ['ElectrumPersonalServer 0.1.6', 1.4]
[i][localhost] set blockchain with height 570055
[i][localhost] can't connect 570068
[i][localhost] requesting block header 570056 in mode backward
[n] switching to localhost:50003:s
[i][localhost] exiting backward mode at 570056
[i][localhost] could connect 570056
[i][localhost] requesting chunk from height 570057
[i][localhost] disconnecting gracefully. Network request timed out.
[n] connecting to localhost:50003:s as new interface
[i][localhost] connection established. version: ['ElectrumPersonalServer 0.1.6', 1.4]
[i][localhost] set blockchain with height 570056
[i][localhost] can't connect 570068
[i][localhost] requesting block header 570057 in mode backward
[n] switching to localhost:50003:s
[i][localhost] exiting backward mode at 570057
[i][localhost] could connect 570057
[i][localhost] requesting block header 570058 in mode catchup
[n] network: retrying connections

Edit, even when up to date, the electrum interface keeps showing it's synchronizing (and doesn't show the green light bottom right)

**Comment by BobleChinois** [comment]
Hi, I had an issue that looks like it's the same than what you describe at the end (synchronizing for ever) : https://github.com/chris-belcher/electrum-personal-server/issues/95
But today it worked and I can't reproduce the error, don't know what happened. Are the logs from Electrum showing anything remarkable?

**Comment by Coinomatron** [comment]
Issue was solved (for now) when using electrum 3.3.4. I'll check the logs and reopen this, should the problem return. Cheers.
